### ISSUE TITLE
Add .well-known

### ISSUE THREAD

**Issue by aaronraimist** [spantaleev/matrix-docker-ansible-deploy#10]
https://matrix.org/docs/spec/client_server/r0.4.0.html#get-well-known-matrix-client

Example: https://matrix.org/.well-known/matrix/client

**Comment by spantaleev** [comment]
This playbook sets up the Matrix server (at `matrix.<domain>` and `riot.<domain>`) and not on the actual `<domain>` server.

As per the specification, the `/.well-known/matrix/client` is supposed to be on the actual `<domain>` server, which is not managed by this playbook.

Because of this, this playbook cannot really set it up for you. Still, we should add documentation somewhere that tells people about it, so they can set it up (similar to how we advise people to set up SRV DNS records for `<domain>` in order to point the Matrix service at `matrix.<domain>`).

-------

To make things simpler to set up though, I think the playbook can generate and serve the appropriate file at `https://matrix.<domain>/.well-known/matrix/client` (even though that's the wrong domain name to set it up at!).

And then, we can tell people to set up `https://<domain>/.well-known/matrix/client` by:

1) simply copying the static file configured by the playbook at `https://matrix.<domain>/.well-known/matrix/client`. This is easy to do and people's only choice if `<domain>` is just some static website server that they can't control

2) or: setting it up more reliably by configuring proxying for that file

We can provide proxying examples. For nginx, it would be something like:

```nginx
server {
	server_name <domain>;

	location /.well-known/matrix {
		proxy_pass https://matrix.<domain>;
	}

	# other configuration
}
```

Method 1) may be easier and a better choice in certain situations, while method 2) is less prone to breakage in case the playbook ever generates the `/.well-known/matrix/client` file differently for some reason (new configuration keys, etc.)

**Comment by spantaleev** [comment]
As of 0d0ccde286ac39, this is now implemented!

The playbook generates the file, as described above.
You're then supposed to either copy it over to the base domain's server or to set up reverse-proxying there.
The documentation describes it in detail, along with example configuration for both nginx and Apache.
