### ISSUE TITLE
Two nginx instances

### ISSUE THREAD

**Issue by ethindp** [spantaleev/matrix-docker-ansible-deploy#1118]
So, I'd like to do something like replacing the docker-provided nginx with one outside a container. However, my approach is a bit different since I want to keep coturn working so I'll need SSL for that.

Essentially, what I'd like to do is have a public-facing nginx server and then have that reverse-proxy to the nginx server in docker. The rationale for this is because for certain browsers, submitting information on a page that's HTTPS but that gets submitted to a non-secure server raises alerts. And I'd like to keep the SSL for coturn, as well.

Is this kind of setup possible, and how would I do it properly?

**Comment by spantaleev** [comment]
Sounds like can use [Method 2: Fronting the integrated nginx reverse-proxy webserver with another reverse-proxy](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-own-webserver.md#method-2-fronting-the-integrated-nginx-reverse-proxy-webserver-with-another-reverse-proxy).

You'd be using the playbook's `matrix-nginx-proxy` nginx webserver to expose services on `127.0.0.1:81` and `127.0.0.1:8449` (for example), and then you'd reverse-proxy whatever you need from your own public-facing nginx webserver.

`matrix_ssl_retrieval_method: none` will automatically disable SSL for Coturn, as per this: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/c6002b0a0d8e878babcd37a6dc3f6070f6955b21/group_vars/matrix_servers#L925-L937

Since you have your own SSL certificates somewhere, you can probably flip `matrix_coturn_tls_enabled` to `true` and adjust the other SSL path variables (and likely `matrix_coturn_container_additional_volumes`, so that you can mount your other certificates into the Coturn container)

**Comment by ethindp** [comment]
Right, but I want to keep SSL for the docker webserver but
reverse-proxy from another. Especially since I'm still learning the
configuration settings for this and I can't deploy my config until I
get this out of the way.

On 6/10/21, Slavi Pantaleev ***@***.***> wrote:
> Sounds like can use [Method 2: Fronting the integrated nginx reverse-proxy
> webserver with another
> reverse-proxy](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-own-webserver.md#method-2-fronting-the-integrated-nginx-reverse-proxy-webserver-with-another-reverse-proxy).
>
> You'd be using the playbook's `matrix-nginx-proxy` nginx webserver to expose
> services on `127.0.0.1:81` and `127.0.0.1:8449` (for example), and then
> you'd reverse-proxy whatever you need from your own public-facing nginx
> webserver.
>
> `matrix_ssl_retrieval_method: none` will automatically disable SSL for
> Coturn, as per this:
> https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/c6002b0a0d8e878babcd37a6dc3f6070f6955b21/group_vars/matrix_servers#L925-L937
>
> Since you have your own SSL certificates somewhere, you can probably flip
> `matrix_coturn_tls_enabled` to `true` and adjust the other SSL path
> variables (and likely `matrix_coturn_container_additional_volumes`, so that
> you can mount your other certificates into the Coturn container)
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/1118#issuecomment-858364731


-- 
Signed,
Ethin D. Probst
