### ISSUE TITLE
Consider downgrading the importance of /.well-known/matrix/server

### ISSUE THREAD

**Issue by aaronraimist** [spantaleev/matrix-docker-ansible-deploy#122]
Most people using this setup shouldn't need it, the SRV record is enough and is a simpler to use

**Comment by spantaleev** [comment]
Unless something changed, from what I understand, it's the SRV record that needs to be gone when Synapse v1.0 gets released.

Delegating via a SRV record requires that the certificate presented by the Matrix server (on `matrix.DOMAIN:8448`) is a certificate valid for the base domain (`DOMAIN`, not `matrix.DOMAIN`).

Of course, a certificate valid for both domains or a wildcard certificate also works.

People who have such a certificate can forego `/.well-known/matrix/server` and just use a SRV record. This is a rare situation though. By default, the playbook obtains Let's Encrypt certificates automatically, for its own domains (`matrix.DOMAIN`, `riot.DOMAIN`, etc.). It generally cannot acquire a certificate for the base domain, as it usually lives on another machine. The playbook also does not obtain dual or wildcard certificates, so advising people into using them is not of much help.

---------

We require delegation via `/.well-known/matrix/server`, because we want to get away from this awkward requirement. Most people host their Matrix machine separately (as we encourage - on `matrix.DOMAIN`) and can't easily obtain certificates for other domains (like `DOMAIN`) from the Matrix machine.

**Comment by aaronraimist** [comment]
> it's the SRV record that needs to be gone when Synapse v1.0 gets released

No this is not true. SRV records are still fully supported and will continue to be supported. See https://youtu.be/dPvis1eEMDM?t=905 to 16:45

Re certificates: I guess I misunderstood since I did run it for months on a separate machine but I guess that was in the era when I didn’t need a proper TLS certificate. For some reason in my head I had the TLS requirements for SRV and well-known reversed.

**Comment by spantaleev** [comment]
This video makes it sound like using well-known is really an edge case. To me, it seems like for any real deployment it shouldn't be.

They talk about "hosting on behalf of someone else", and that's exactly what we do. We want our identifiers to include the base domain, yet we want to host Matrix services elsewhere - on the `matrix.DOMAIN` machine. We host Matrix services on `matrix.DOMAIN` on behalf of the people owning the base `DOMAIN`. These people happen to be us again.

As far as I understand, the only people who don't need to implement well-known and can get by with just SRV records are people who:

- either host Matrix services on the base domain itself. I doubt there are many people willing to mix-in Matrix services with their other stuff.

- or host Matrix services on a dedicated `matrix.` (or similar) subdomain and have that same subdomain act as their `server_name`. Those people need to live with ugly identifiers (e.g. `@user:matrix.DOMAIN`), so not many would like to do this either.

- or host Matrix services separately (`matrix.` or similar subdomain), but use the base domain as their `server_name`. For them, the base domain is usually another separate machine. Those people need to somehow install a base domain certificate on the `matrix.` server. This is feasible, but usually complicated.

I think the video says a few things that can either be interpreted incorrectly.

Eric saying:

> `.well-known` adds complexity, because you have to have  a certificate at a different name than your homeserver

could be taken to mean one of these:

- not only do you need a certificate for your Matrix server (`matrix.DOMAIN`), but you're also required to have a certificate for the base domain, just so you could serve `https://DOMAIN/.well-known/matrix/server`. That's what he meant, I believe.

- your homeserver needs to be served with a certificate for a different name. Maybe that's what you were lead to believe? This is the case for SRV record delegation, which is where all this insanity and complication comes from. Well, as far as I know, it's the XMPP folks who invented this..

**Comment by aaronraimist** [comment]
> or host Matrix services separately (matrix. or similar subdomain), but use the base domain as their server_name.  For them, the base domain is usually another separate machine.

I'm not sure if that is true. I wouldn't say usually. I think a lot of people who are just hosting a small server for their family are only going to have one server. So they'll host synapse on a subdomain but they'll have one web server sitting over both the subdomain and the base domain. That's how I do it now. So in that case an SRV record is easier or at least the same level of easy as well-known.

Anyway I'll close this now as .well-known does make sense for people who want to use two different servers.
