### ISSUE TITLE
Playbook installation fails, while ensuring Mautrix Telegram image is pulled

### ISSUE THREAD

**Issue by N07070** [spantaleev/matrix-docker-ansible-deploy#1239]
On an already installed server with this playbook, I've update it by git-pulling, and launching the playbook. It fails as such ; 

```
TASK [matrix-bridge-mautrix-telegram : Ensure Mautrix Telegram image is pulled] ************************
fatal: [matrix.domain]: FAILED! => changed=false 
  msg: 'Error pulling image dock.mau.dev/mautrix/telegram:v0.9.0 - 404 Client Error: Not Found ("manifest for dock.mau.dev/mautrix/telegram:v0.9.0 not found: manifest unknown: manifest unknown")'

PLAY RECAP *********************************************************************************************
domain         : ok=82   changed=9    unreachable=0    failed=1    skipped=429  rescued=0    ignored=0   
```

Is there anything I should do ?

I've looked for similar issues in this repo.

**Comment by N07070** [comment]
Seems like it's trying to pull a docker image from a dockler repo maintained by mau.dev. This docker repo seems offline, which might be the issue.

**Comment by spantaleev** [comment]
This seems to be a regression caused by #1237.

There's no image tagged with `v0.9.0` in the `dock.mau.dev/mautrix/telegram` container registry. Seems like there are no version-tagged releases there are all. We should either switch to `:latest` for now (likely not a good idea), or revert to the old registry (`dock.mau.dev/tulir/mautrix-telegram`) until a version-tagged release is added.

**Comment by tulir** [comment]
Oh right, I intended to make new releases for most of the bridges, but forgot to release mautrix-telegram v0.10.1

**Comment by N07070** [comment]
Created a pull request to fix this issue. If you want to merge it @spantaleev , I've run tests on my own server.

**Comment by spantaleev** [comment]
Thanks for fixing it!
