### ISSUE TITLE
Installation of 'systemd-timesyncd' fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by cherbst** [spantaleev/matrix-docker-ansible-deploy#1302]
The message is:
`No package matching 'systemd-timesyncd' is available`
On Ubuntu 18.04 'systemd-timesyncd' is provided by the package 'systemd' that's why the installation fails.

**Comment by spantaleev** [comment]
My testing showed that `systemd-timesyncd` is not available on Ubuntu 18.04 at all, neither as a separate `systemd-timesyncd` package, nor as part of the main `systemd` package.

Because of this, I've made Ubuntu 18.04 use ntp instead.

If you think `systemd-timesyncd` is available on Ubuntu 18.04 somehow, let me know and we can revisit this.
