### ISSUE TITLE
Add matrix-nginx-proxy option to remove X-Forwarded-For headers

### ISSUE THREAD

**Issue by wegotshrimp** [spantaleev/matrix-docker-ansible-deploy#1393]
When Method 2 on the [Using your own webserver](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-own-webserver.md#method-2-fronting-the-integrated-nginx-reverse-proxy-webserver-with-another-reverse-proxy) page, I'm noticing that the connections are all listed as coming from my other reverse proxy for my users.

After looking, I believe that [matrix-domain.conf](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-domain.conf.j2) setting the X-Forwarded-For (and X-Forwarded-Proto) headers again is whats causing it. I commented out the proxy_set_header directives on my generated confs and got the real remote IPs of users connecting.

Perhaps a matrix_nginx_proxy_forward_for boolean (default true) to enabled/disable their inclusion?

**Comment by spantaleev** [comment]
Perhaps instead of not setting `X-Forwarded-For`, it may be better to append your other reverse-proxy's IP address to it.

Seems like if you replace `proxy_set_header X-Forwarded-For $remote_addr;` with `proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;`, it should work.

Settings this to `$proxy_add_x_forwarded_for` for everyone by default is not a good idea, as it would allow people to "pretend" to be fronting your reverse-proxy with another reverse-proxy and make you trust that the Client IP is different. So we shouldn't use this as a default.

---------

If you confirm that the above fix works for you, we can make this configurable via a `matrix_nginx_proxy_x_forwarded_for` variable, which defaults (`roles/matrix-nginx-proxy/defaults/main.yml`) to:

```yaml
# Specifies what to use for the X-Forwarded-For variable.
# If you're fronting the nginx reverse-proxy with additional reverse-proxy servers,
# you may wish to set this to '$proxy_add_x_forwarded_for' instead.
matrix_nginx_proxy_x_forwarded_for: '$remote_addr'
```

**Comment by wegotshrimp** [comment]
Yep, setting `X-Forwarded-For` to `$proxy_add_x_forwarded_for` rather than `$remote_addr` has done it for me, primarily in the matrix-domain.conf file. That configuration flag would be amazing, thank you!

**Comment by spantaleev** [comment]
This is now customizable via `matrix_nginx_proxy_x_forwarded_for`. Thanks for verifying that it helps! :+1:
