### ISSUE TITLE
Jitsi authentification gives a weird error since the new jitsi authentification system

### ISSUE THREAD

**Issue by GodGoldfish** [spantaleev/matrix-docker-ansible-deploy#1483]
Hi,
i recently updated my matrix-docker-ansible git and realize that i needed to change my vars.yml because the config for the jitsi authentification changed recently and that's what i did, i precise that i wiped the jitsi data, and then when the ansible setup arrived to the jitsi config an error occur and says something is wrong with jitsi-prosody, so depend of the password and/or the username even if it's only with letter and number sometimes it works and some other times it doesn't.
am i doing something wrong ?

**Comment by spantaleev** [comment]
Also related to: https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/1474

.. and https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/1464

-------

Not sure if you're doing something wrong, or we have a bug.. Or our new way for doing things (in #1464) broke compatibility with the old way.

I'm not using Jitsi, so I have little interest in investigating this complexity and testing out the old/new stuff. It'd be nice if someone who uses Jitsi would step in and do that.

**Comment by GodGoldfish** [comment]
> Owner

Like @ubergeek77 said the solution is to enter those commands (two times) :
```
ansible-playbook -i inventory/hosts setup.yml --tags=setup-all,start
ansible-playbook -i inventory/hosts setup.yml --tags=setup-all,start
```
and then jitsi finally accept the configuration it's not normal to use these commands two times but it fix the problem.

**Comment by ubergeek77** [comment]
I think the best solution to this problem, outside of nailing down Jitsi-specific issues, is to simply put a warning in the maintenance guide:

https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/maintenance-upgrading-services.md

Something to the effect of:

*"When upgrading services with non-backwards-compatible changes, it is sometimes necessary to run these commands twice. If you encounter a problem, please run these commands twice before filing an issue."*

However, I do not believe this issue is necessarily specific to Jitsi. Based on the behavior I observed, if this repository ships an updated script that is intended to run against a newer version of a service, it ***will*** be run on the old version of the service first, causing problems. In other words, there is a dependency problem - new Docker containers for services should be pulled and deployed first, *before* running any new deployment scripts on them.

I think that is an issue of its own worth addressing, as it is likely to happen again in the future for other services. But I would love to hear your thoughts on this, @spantaleev .

**Comment by spantaleev** [comment]
@ubergeek77, perhaps we can replace `state: started` with `state: restarted` in `roles/matrix-jitsi/tasks/util/setup_jitsi_auth.yml`, at least when `matrix_jitsi_prosody_systemd_service_result.changed`. This would probably be a simple solution to our current problem.

**Comment by ubergeek77** [comment]
That sounds like a plan to me!

Thank you!
