### ISSUE TITLE
Installation fails in Debian 11.2.0 if no sudo is installed

### ISSUE THREAD

**Issue by silasdb** [spantaleev/matrix-docker-ansible-deploy#1492]
In a very minimal Debian installation I got:

```
TASK [matrix-nginx-proxy : Generate SSL certificate] ***************************
fatal: [matrix.saturn.xyz]: FAILED! => changed=false 
  module_stderr: |-
    /bin/sh: 1: sudo: not found
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 127
```

It worked after I installed sudo. Maybe the playbook should install sudo or is this too elementary too bother about that?

**Comment by spantaleev** [comment]
This happens here: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/78133e16dbe747bfb8d5b03a45364a93779a9c23/roles/matrix-nginx-proxy/tasks/ssl/setup_ssl_self_signed_obtain_for_domain.yml#L30-L42

It seems like it's caused by us using `become` and `become_user`, so that when the certificate file is generated (using the `openssl req ..` command), it'd be owned by the `matrix` user.

----------

Instead of installing `sudo`, we may remove the need for using `become_user` by having 2 steps:

- the same generation step we have now (but without the `become` and `become_user` parts). The generated certificate and key will likely be owned by `root` at this point
- a new step which adjusts the file ownership (see below)

I've implemented this in 948c4111069f2.

Another benefit of doing this (besides not requiring `sudo`) is that future changes to `matrix_user_username` or `matrix_user_groupname` will correctly adjust the ownership of these files as well.

---------

Installing `sudo` may be necessary elsewhere (for other tasks). If this comes up in the future, we may address it by installing `sudo` (as part of the `matrix-base` role) for the various distros we support.
