### ISSUE TITLE
Update matrix-bridge-appservice-slack to version 1.10.0

### ISSUE THREAD

**Issue by GoliathLabs** [spantaleev/matrix-docker-ansible-deploy#1508]
Hello!
I would like to know if there is a reason why we are still on version 1.8.0, although there have been a few updates since October. I just ask before in this thread here, otherwise I would like to open a PR to update the version used 😄

**Comment by spantaleev** [comment]
We're still on an old version, because no one has bumped the version yet and verified that the new one works.

One would ideally:
- go through [the bridge's changelog](https://github.com/matrix-org/matrix-appservice-slack/blob/develop/CHANGELOG.md) for all previous releases, to look for potential trouble and adjust the playbook to fix it
- bump the version in the playbook
- adjust our configuration template (`roles/matrix-bridge-appservice-slack/templates/config.yaml.j2`) to match a potentially updated [sample configuration used by the bridge](https://github.com/matrix-org/matrix-appservice-slack/tree/1.10.0/config). Looks like we're currently using a pretty minimal configuration though. Maybe there's no need to do anything.
- verify that the new version of the bridge works and there's no data loss for existing users, etc.

Updating takes effort and requires one to be using the bridge, so that they can verify that it works. Blindly bumping the version is generally not done.

PRs are welcome.
