### ISSUE TITLE
Another server_name

### ISSUE THREAD

**Issue by demontefacto** [spantaleev/matrix-docker-ansible-deploy#1596]
Hello.  First i would like say thank you for these playbooks. They are awesome. Second I would like to ask, how can I change the server name?

I would like run matrix server on another domain than matrix.example.com. For example just im.example.com. How can I do that with this? If I set the server_name to im.example.com, this system create another subdomain matrix and finaly it wants to generate certificates for matrix.im.example.com

Thank you for your answer

**Comment by spantaleev** [comment]
With our setup, by default the base domain is `example.com` with services actually hosted at `matrix.example.com`.

You're changing the base domain to `im.example.com`, so with our default configuration services are expected to be hosted at `matrix.im.example.com`.

------

If you'd like the base domain to be `example.com`, but services to be hosted at `im.example.com` (instead of `matrix.example.com`), you can override the `matrix_server_fqn_matrix` variable in your `vars.yml` file. Here's the default definition of the `matrix_server_fqn_matrix` variable: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/d3983a0f04a9922f3797aba4952ad6004ef17e4f/roles/matrix-base/defaults/main.yml#L24
