### ISSUE TITLE
email2matrix unable to start on linux/amd64

### ISSUE THREAD

**Issue by Traace** [spantaleev/matrix-docker-ansible-deploy#1605]
Did a fresh pull and update a few minutes ago.

Now email2matrix fails to start with error: "standard_init_linux.go:228: exec user process caused: exec format error"

The container architecture is listed as amd64 in "docker image inspect devture/email2matrix:1.0.2" but is seems like the exec inside the container is for arm

The last commit I could find regarding email2matrix and arm is this: https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/ccb85b31a4eda611f9105833e1d0525db9175187

**Comment by spantaleev** [comment]
Nice catch! It turned out to a silly building mistake, which was fixed here: https://github.com/devture/email2matrix/commit/49f966d6cc789423b7ba7100ea5d3523193345f3

.. which is released as 1.0.3. Fixed in https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/b244ab477ccace8774c1bd83cc5befa52a073104

**Comment by Traace** [comment]
Thank you very much :)

Will update this evening
