### ISSUE TITLE
Unable to embed grafana as widget

### ISSUE THREAD

**Issue by ghost** [spantaleev/matrix-docker-ansible-deploy#1626]
I'm trying to embed a Grafana into a room as a widget. But whatever I do, it will not embed. 
[https://scalar.vector.im/api/widgets/embeddable?curl=https://stats.exapmle.com/d/000000012/my-network-matrix-stats?orgId=1&refresh=5m&kiosk&from=now-24h&to=now](https://scalar.vector.im/api/widgets/embeddable?curl=https://stats.exapmle.com/d/000000012/my-network-matrix-stats?orgId=1&refresh=5m&kiosk&from=now-24h&to=now) to check if the url is embeddable and this is where the response is
```
{"message":"Embedding content forbidden - X-Frame-Options: DENY","user_error":"X-Frame-Options: DENY"}
```
my vars.yml
```
# Grafana
matrix_prometheus_enabled: true
matrix_prometheus_node_exporter_enabled: true
matrix_grafana_enabled: true
matrix_grafana_anonymous_access: true
matrix_grafana_anonymous_access_org_name: 'MyNewOrg'
matrix_grafana_default_admin_user: "myadm"
matrix_grafana_default_admin_password: "my-pass-word"
```

**Comment by spantaleev** [comment]
At first I thought it's because we were preventing framing via our `matrix-nginx-proxy` configuration for the Grafana `server`, but then I looked at the configuration: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/cfba9b2cf5f210891ac95035f17e6dbafbf2a808/roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-grafana.conf.j2#L12-L16

Looks like Grafana is sending an `X-Frame-Options` header on its own, because its [`allow_embedding`](https://grafana.com/docs/grafana/latest/administration/configuration/#allow_embedding) configuration key defaults to `false`.

I've made this configuration key configurable in f0ab2ec50696a0108f4ac857b116ffb04f9cc236, so if you were to update your playbook, add `matrix_grafana_allow_embedding: true` to your `vars.yml` configuration and rebuild your Grafana setup (`ansible-playbook .... --tags=setup-grafana,start`), it should become possible to embed.
