### ISSUE TITLE
Moving Matrix data outside Synapse server

### ISSUE THREAD

**Issue by lunaisnotaboy** [spantaleev/matrix-docker-ansible-deploy#1641]
Hi there. I run a Matrix server running this tool, and while I think it is an amazing tool, Ansible always slows the server to a halt. As this is the case, I've decided to just move to a Synapse server set up manually instead of one set up by this playbook. However, I cannot find docs on how to export the data, as it always assumes that you are moving to another server via Ansible.

Is this even possible, or am I just missing something?

**Comment by spantaleev** [comment]
Ansible slowing down the server sounds odd. Even if it does have an effect, it should last only *while* Ansible is running to update your server (usually a matter of minutes).

If you think it's running Docker containers that are slowing things down, that also sounds unlikely. Containers are just regular Linux processes isolated into control groups, etc. There's *no* overhead.

----------

That said, you should be able to migrate away from this Ansible/Docker setup and into one that runs manually with or without containers.

You should:

- [back up Postgres](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/maintenance-postgres.md#backing-up-postgresql) and restore the generated Postgres dump onto your new Postgres server
- migrate the Synapse `media_store` (`/matrix/synapse/storage/media-store`) to your new server. You may need to adjust the user permissions on these files to match whatever your new server expects
- migrate the Synapse signing key to your new server (`/matrix/synapse/config/matrix.DOMAIN.signing.key`)

**Comment by lunaisnotaboy** [comment]
Thank you for your response. I appreciate you explaining how to migrate everything. As for what was slowing down the server, I honestly have no idea. All I know is that the Docker containers were slowing the entire server down, and that I didn't have this problem when I set up another test server on the same hardware with the same components (Synapse, Element, Dimension, etc.).

I'm honestly wondering if it's the hardware at this point, but I can't do anything about that.

If I find out exactly what was slowing everything down, I'll be sure to post it here in the unlikely event someone else is having this same problem.

**Comment by brandon-a** [comment]
@spantaleev I am also trying to migrate my synapse server. My issue is that my server is completely out of disk space and I am unable to run any services due to this issue as well. I cannot start the services to trim the database, etc. 

Anyway, would you happen to know if there is any way to access the files you mentioned above without starting the docker containers?

I would greatly appreciate any guidance you may have, thanks!

**Comment by spantaleev** [comment]
@brandon-a, you can move all of `/matrix` to a new server with more disk space and rebuild things there. See our [Migrating to new server](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/maintenance-migrating.md#migrating-to-new-server) documentation.

---------

**Otherwise**, if you'd like to do something on the current (out-of-disk-space) server, you may be able to:
- stop all services (`ansible-playbook ...... --tags=stop`)
- move Synapse's media store away - `rsync` all of `/matrix/synapse/storage/media-store` elsewhere (on another server or your home computer) and delete it from the Matrix server. Doing that should free up some (see how much `du -hs /matrix/synapse/storage/media-store`) disk space.
- now you should be able to at least start Postgres (`systemctl start matrix-postgres`) and do a backup. By modifying the backup command a bit, you may be able to get the backup stored directly on another server (in case you don't have enough on the current one).

In any case, the **Migrating to new server** guide is probably better for you, if you'll be migrating for a new server **with the same CPU architecture**. Better to copy all of `/matrix` and re-run the playbook to initialize things, instead of doing database backups, etc., and restoring those manually.

**Comment by brandon-a** [comment]
Thank you! I made the silly mistake of thinking `/matrix` did not exist since I did not have permission to access it. Following your steps above worked for me! Thanks again!
