### ISSUE TITLE
Image Display

### ISSUE THREAD

**Issue by cardinalfan1** [spantaleev/matrix-docker-ansible-deploy#1671]
**Playbook Configuration**:

I’m not exactly sure if this is relevant. I will post if needed.

**Matrix Server:**
 - OS: Ubuntu 20.04
 - Architecture : amd64

**Problem description**:

I use the mx puppet discord bridge which works fine. When my discord channel (which receives webhooks) gets a notification that includes an image attachment, that gets posted to the matrix channel as a url.  This is an example of the json from the element client: 

```

"body" : "**Testest** has just been added on local\n\n----\n##### (<url>\nImage: <image url>",

```

This all displays fine, but the image is displayed on the screen as a small cropped image… and when I click on the image it opens the link in the browser. I would like for it to display either as a thumbnail or if clicked, to directly open the image rather than opening up the browser. So I’m trying to figure out:

- is this normal and expected behavior? For it to display just a small part of the image and to open as an external link when clicked?
- is this a problem with the discord bridge for putting it as an external url that activates the url preview system?
- Is it a problem with synapse for not pulling the image into the media repo and making the client render it locally?
- Or is it problem with element for the display behavior?

appreciate the help!

**Client (please complete the following information):**
 - Element , on any device (browser, iOS, etc)

**Comment by spantaleev** [comment]
I suppose that this is some combined message - image + description.

Maybe that's how [mx-puppet-discord](https://github.com/matrix-discord/mx-puppet-discord) sends such combined messages -- by forwarding the image URL, instead of sending an inline image.

In any case, this has nothing to do with the playbook. Either the bridge is buggy (or that's the best it can do, since Matrix still does **not** have such "combined messages"), or whatever sends the message via the webhook is sending something weird. You should report that issue to the bridge developers, not to us.

However, mx-puppet-discord has been unmaintained for a long time (with some activity starting up again lately), so I'm not sure how far you can get by reporting issues there.
