### ISSUE TITLE
Synapse S3 Storage Provider instead of Goofys?

### ISSUE THREAD

**Issue by tompinzler** [spantaleev/matrix-docker-ansible-deploy#176]
Just getting started with that playbook (thanks for creating it!) and want to use S3 as a storage back-end. I realized that you are integrating S3 using Goofys instead of the official [synapse-s3-storage-provider](https://github.com/matrix-org/synapse-s3-storage-provider).

I would think that Goofys is more like a workaround for applications that don't natively support S3.

Wouldn't synapse-s3-storage-provider be the natural choice to connect Matrix to S3?

**Comment by spantaleev** [comment]
You're right! Using Goofys is a workaround (and quite hacky implementation-wise).
It'd be much better if we support something else (also see #67).

A few things that are worrisome about [synapse-s3-storage-provider](https://github.com/matrix-org/synapse-s3-storage-provider):
- requires [boto3](https://github.com/boto/boto3), so likely just adding the module to the Synapse Docker container is not enough to enable it. Unless the Docker image already includes boto3 (doubtful).
- it doesn't support other (S3-like) object stores (work happening/stuck here: https://github.com/matrix-org/synapse-s3-storage-provider/pull/13). Even our Goofys usage didn't until recently though (see #132)
- seems unmaintained (some seemingly important pull requests being stuck; some issues saying "not working"). This may just be a wrong first impression though.
- seems like Synapse would still store files locally [according to this comment](https://github.com/matrix-org/synapse-s3-storage-provider/issues/6#issuecomment-419601139) as well as remotely on S3. What happens when the local cache fills up? Does Synapse trim it before we run out of disk space or?

We should try to clear some of these up, but.. for now, it seems like relying on the Goofys workaround is easier and safer.

Also, adding support for synapse-s3-storage-provider doesn't mean that we need to get rid of Goofys or support all of the features we have there. It can be a completely separate option that we support, with its own pros and cons. But before we do that, we should figure out what we gain and whether anyone gains enough to spend the time to work on it.

**Comment by tompinzler** [comment]
Thanks for the detailed answer. Totally understand your decision now.

**Comment by ptman** [comment]
synapse-s3-storage-provider seems to support other S3-compatible stores now

**Comment by dotZoki** [comment]
It would be nice if support for synapse-s3-storage-provider is added.

**Comment by shalzz** [comment]
Hi, time to maybe revisit this?

Let's at least reopen this issue if we're not completely against supporting [synapse-s3-storage-provider](https://github.com/matrix-org/synapse-s3-storage-provider).

**Comment by spantaleev** [comment]
Reopening issues does not do much. A PR would be more helpful ;)

**Comment by shalzz** [comment]
Yes, just to signal that a PR for this would then indeed be accepted.
