### ISSUE TITLE
TemplatingError, unknown test 'ne'

### ISSUE THREAD

**Issue by tctovsli** [spantaleev/matrix-docker-ansible-deploy#1772]
When I try running the playbook on a fully updated CentOS 7 machine, the playbook fails with an error that the test 'ne' is unknown.
I suspect it is not supported in older versions of Jinja2.

https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/dd83d88cb04791a19f343fd3750f974a3a19c64b/roles/matrix-coturn/templates/turnserver.conf.j2#L8

**Comment by spantaleev** [comment]
Which Jinja2 version is this on? `ansible --version` should show that.

Looks like we either need to rework this somehow, or to just raise our minimum version requirements for Ansible (and thus, Jinja2).

As an alternative, you can try running (a recent version of) Ansible in a container. See `docs/ansible.md`.

**Comment by tctovsli** [comment]
It doesn't specify which jinja2-version it is, but it's Ansible 2.9.27 with python 2.7.5

`yum` indicates that I have python-jinja2 version 2.7.2-4 installed.

**Comment by tctovsli** [comment]
I tried running ansible from docker, but my `hosts`-file has set `ansible_connection=local`, so Ansible fails on the step where it checks if docker is available. And when try to remove that setting, it tries to SSH to the public IP of my node, which doesn't accept SSH-connections.

What is the best way to address this? Point `ansible_host` to the private IP and specifying the public IP for `matrix_coturn_turn_external_ip_address`?

**Comment by spantaleev** [comment]
There may be some way to run Ansible in a container and to target the current system (`ansible_connection=community.docker.nsenter`).

If you use the [`nsenter` tag of the `devture/ansible` container image](https://hub.docker.com/r/devture/ansible/tags?page=1&name=nsenter), it might work.

See [Usage against the same host](https://github.com/devture/docker-ansible/tree/nsenter#usage-against-the-same-host) in the README of the `nsenter` branch of https://github.com/devture/docker-ansible

You'll need:

```
--privileged \
--pid=host \
```

when starting it.. Also, make sure you're using `:nsenter`, not `:latest`. The README is somewhat inaccurate when it comes to this.

So.. I think you need:

```sh
cd matrix-docker-ansible-deploy

docker run -it --rm \
--privileged \
--pid=host \
-w /work \
-v `pwd`:/work \
--entrypoint=/bin/sh \
docker.io/devture/ansible:nsenter
```

------

You may be able to keep `ansible_host` as is (pointed to the public IP). With `ansible_connection=community.docker.nsenter`, it will probably not attempt to connect via IP at all, so it shouldn't cause any trouble.

Otherwise, you're right. If you're changing `ansible_host` to something else, you'll need to explicitly define your public IP in `matrix_coturn_turn_external_ip_address`.

-----

Let me know how it goes!

**Comment by tctovsli** [comment]
It worked, sort of. The next error I encountered was this:
```
TASK [matrix-base : Ensure Matrix network is created in Docker] **************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'requests'                                                                                                                                    
fatal: [matrix.midlertidig.online]: FAILED! => changed=false 
  msg: 'Failed to import the required Python library (Docker SDK for Python: docker above 5.0.0 (Python >= 3.6) or docker before 5.0.0 (Python 2.7) or docker-py (Python 2.6)) on tc-matrix''s Python /usr/bin/python3.6. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter, for example via `pip install docker` (Python >= 3.6) or `pip install docker==4.4.4` (Python 2.7) or `pip install docker-py` (Python 2.6). The error was: No module named ''requests''' 
```

**Comment by spantaleev** [comment]
I could not reproduce this. This may have something to do with the Python version installed on your CentOS 7 server.

**Comment by chagai95** [comment]
I'm running into the same problem, also a CentOS 7 server...

**Comment by spantaleev** [comment]
CentOS 7 is insanely old. Running old Ansible on old CentOS 7 is scary to even think about. Consider upgrading your Ansible / Jinja version or run Ansible in a container.
