### ISSUE TITLE
Self-signed certificates persist after switching back to Let's Encrypt

### ISSUE THREAD

**Issue by Addono** [spantaleev/matrix-docker-ansible-deploy#184]
Initially I ran the Ansible script configured such that it would generate self-signed certificates. Later, when I switched back to Let's Encrypt the certificates were successfully retrieved, however the old self-signed certificates were still being served by nginx.

# Expected
When switching from `matrix_ssl_retrieval_method: self-signed` back to `matrix_ssl_retrieval_method: lets-encrypt`, then the newly generated Let's Encrypt certificates will be used.

# Workaround
I manually moved the newly generated Let's Encrypt certificates to the location of the self-signed certificates.

```bash
mv  /matrix/ssl/config/live/matrix.{my-domain}/  /matrix/ssl/config/live/matrix.{my-domain}-self/
mv  /matrix/ssl/config/live/matrix.{my-domain}-0001/  /matrix/ssl/config/live/matrix.{my-domain}/

mv  /matrix/ssl/config/live/riot.{my-domain}/  /matrix/ssl/config/live/riot.{my-domain}-self/
mv  /matrix/ssl/config/live/riot.{my-domain}-0001/  /matrix/ssl/config/live/riot.{my-domain}/
```

**Comment by spantaleev** [comment]
Thanks for taking the time to report this!

I'm not sure what would be a good way to solve it.

We could:

- (potential solution 1) change `roles/matrix-nginx-proxy/tasks/ssl/setup_ssl_lets_encrypt_obtain_for_domain.yml` to check each certificate file using something like ` openssl x509 -in fullchain.pem -text | grep "Let's Encrypt"`. If it's not from Let's Encrypt, we would delete the existing certificate files and retrieve a new one. I don't like this, because it requires `openssl` to be installed. It also introduces a runtime cost to running the playbook for all playbook users, while fixing an edge case that rarely happens.

- (potential solution 2) or: change `roles/matrix-nginx-proxy/tasks/ssl/main.yml` have the playbook set up a marker/state file somewhere on the filesystem (`/matrix/ssl/retrieval_method`) which contains the last retrieval method (`matrix_ssl_retrieval_method`) that was successfully used. If the last-used method doesn't match the currently-used method, it could delete the certificate directories and start from scratch. This also introduces a runtime cost and additional complexity, but sounds like a better solution (at least no additional dependencies and hacky grep-usage is involved).

If you'd like to spend time on this (ideally on "potential solution 2"), I'd be happy to merge a pull request!
It's probably better if we just leave this edge case alone though.
