### ISSUE TITLE
Reverse proxy nginx can't access docker containers or static files under /matrix

### ISSUE THREAD

**Issue by ethindp** [spantaleev/matrix-docker-ansible-deploy#1859]
So, I've just moved my matrix server to a new server with SELinux and am running into a weird problem where nginx can't access anything on the matrix side of things. Whenever it tries, it gets a 404 back. It also can't read anything under /matrix/static-files, even though I've tried changing the labels of the files and even adding the nginx user to the matrix group. I'm extremely confused -- what am I missing? The docs don't say anything about working with selinux or on SELinux-enabled systems at all.

**Comment by spantaleev** [comment]
Some roles try to set `z`/`Z` labels on volumes, but.. We generally don't support SELinux. Or at least, I believe most of us don't use SELinux, so it's not tested. YMMV with it.

If you'd like to submit a PR that improves the state of SELinux support, that'd be nice, but.. from what I gather, it requires that we use `docker run -v ..` (instead of `docker run --mount ..`) for mounting volumes, which is not great. From what I remember, Docker folks recommend using `--mount` instead of `-v`. There's also the nasty side-effect of `-v` auto-creating a missing file/directory **as a directory**, which can hide some problems with missing files/directories and create directory trees that you don't expect. So we'd like to avoid using `-v` if possible.

**Comment by ethindp** [comment]
@spantaleev According to docker, the `:z`/`:Z` stuff is available with `--mount`. And getting SELinux working with things is pretty easy, it looks like. I'd rather not disable SELinux just to run Matrix -- that seems like a very bad idea.

**Comment by ethindp** [comment]
Well damn, looks like I'll have to disable it after all. Man, that's sad -- SELinux is a great tool to enhance the security of a Linux system.

**Comment by spantaleev** [comment]
It is a great tool, but.. it probably requires multiple people to dedicate their lives to it to make things work ;)

If you've got some quick fixes that get the core components working, it'd be great, but it seems like it's more difficult?

**Comment by ethindp** [comment]
@spantaleev I'd love to, but I have no idea how so... Yeah. Gonna close this for now.
