### ISSUE TITLE
Setting up bridges not supported by the playbook

### ISSUE THREAD

**Issue by kingoftheconnors** [spantaleev/matrix-docker-ansible-deploy#186]
I am trying to set up the matrix-puppet-groupme bridge to bridge a discord channel to a groupme channel. The readme says to update the `homeserver.yaml`'s `app_service_config_files` list and then restart the homeserver.

How do you do that without breaking it?

**Comment by spantaleev** [comment]
You generally need to do 2 things:

- make the appservice `.yaml` file available to the Synapse container. You can do this by setting the `matrix_synapse_container_additional_volumes` variable. See `roles/matrix-synapse/defaults/main.yml` for information about it

- tell Synapse about the additional appservice files you would like loaded. You can do this by setting the `matrix_synapse_app_service_config_files` variable. Again, see `roles/matrix-synapse/defaults/main.yml` for information about it. Note that this should point to the in-container path.

After that, re-run the playbook (`--tags=setup-all,start`).

------------

Ideally, we would add support for the GroupMe bridge and this would be done automatically (by the playbook).

Adding support for a new bridge is relatively simple. There are already 5 bridge-roles (see `roles/matrix-bridge*`) to use as a template.

However, it doesn't seem like there's a Docker image for [matrix-puppet-groupme](https://github.com/matrix-hacks/matrix-puppet-groupme) yet, which needs to be solved first.

**Comment by kingoftheconnors** [comment]
I notice `matrix_synapse_container_additional_volumes` is supposed to contain objects with three variables. For a groupme bridge, would it look like:
```
matrix_synapse_container_additional_volumes: [{"src": "kingoftheconnors/matrix-puppet-groupme:latest", "dst": "{{matrix_base_data_path}}/matrix-puppet-groupme", "options": "rw"}]
```
Or am I reading it wrong?

**Comment by spantaleev** [comment]
`src` and `dst` are file paths to the "registration YAML file" for the bridge.

Bridges usually have a command that can be invoked that generates a `registration.yml` from the config file.

Once you have the registration file, you use `matrix_synapse_container_additional_volumes` and pass:
- `src` - the filesystem path to the registration.yaml file **on the server** (e.g. `/matrix/groupme/registration.yml`)
- `dst` - the filesystem path where that same file will be made available **inside the `matrix-synapse` container** (e.g. `/app-registration/puppet-groupme.yml`)
- `options` - `ro` (readonly) would be sufficient and preferrable, as Synapse doesn't need to write to the file

Example:

```yaml
matrix_synapse_container_additional_volumes:
- src: /matrix/groupme/registration.yml
  dst: /app-registration/puppet-groupme.yml
  options: ro
```

(Of course your list syntax also works, but the above looks cleaner as it doesn't put everything in one very long line)

----

The corresponding `matrix_synapse_app_service_config_files` to the above would be something like:

```yaml
matrix_synapse_app_service_config_files:
- /app-registration/puppet-groupme.yml
```

---

Looks like you've created your own Docker image.
You would need to run that somehow (either manually or through systemd).

You don't pass the name of your Docker image to the playbook. It doesn't care about it and won't start it for you, unless you add proper support for that (by creating a `matrix-bridge-puppet-groupme` role).

Once you get things working manually, and provided you have a public Docker image for the groupme bridge, it should be easy to automate it by making it part of the playbook (a `matrix-bridge-puppet-groupme` role).

**Comment by kingoftheconnors** [comment]
Thanks! That helps a lot.

> You don't pass the name of your Docker image to the playbook. It doesn't care about it and won't start it for you, unless you add proper support for that (by creating a matrix-bridge-puppet-groupme role).

That confuses me. Much like in the roles, won't the image (or maybe the project's repo itself?) have to be placed somewhere in the server and then referenced with some sort of  `matrix_puppet_groupme_base_path` variable? How does Synapse know where the `index.js` file is to run? Does it just assume it's in the same file as where the registration file? Does that mean I have to somehow install my image onto the `matrix-synapse` image before the server starts? Is this pulled docker image the one found on my server at `/matrix/...`?

**Comment by spantaleev** [comment]
If you observe the other bridge roles (see any `roles/matrix-bridge-*` directory), you'll notice that they execute many many Ansible tasks (`./roles/matrix-bridge-SOMETHING/tasks/setup_instal.yml`), which set things up. Example:
- an initial configuration file is created from a template (the template lives in the role's `./templates/` directory)
- a one-off Docker container command is started, running  the bridge image and asking it to generate a registration file from the configuration file
- a systemd service file is put in place, which would start the service (in a Docker container) in the future -- it contains a long `docker run` command that actually starts the bridge
- the registration file is mounted in the Synapse container by adding it to `matrix_synapse_container_additional_volumes`
- the registration file is provided to Synapse's configuration by adding it to `matrix_synapse_app_service_config_files`
- the bridge registers its systemd service file in `matrix_systemd_services_list`, so that it gets automatically started by the playbook when `--tags=start` is done (actually registration happens before any of the above tasks, from `./init.yml`)

Depending on the type of bridge, there may be other steps, but generally the flow is as described above.
Take a look at any role to see how things are done.

You can create your own bridge role (don't forget to also register it in `setup.yml` in the main project directory) as a copy of some other bridge role and customize it until it works.

.. or you can follow the steps somewhat manually and accomplish the same. Doing it manually might be easier, until you've figured things out. Each bridge Docker image is different and created by a different person. What works for one bridge (and its Docker image) may not work for another. Special changes may need to be done to the `docker run` command.

----------

If you'd like to get more help (and quicker), I suggest you:
- join the [support room for the playbook](https://github.com/spantaleev/matrix-docker-ansible-deploy#support)
- and/or join the [support room for the matrix-puppet-groupme bridge](https://github.com/matrix-hacks/matrix-puppet-groupme#discussion-help-and-support).. Although, you seem to have built your own Docker image of that bridge, so they may not be of too much help when it comes to running it in Docker. Worth a shot for questions about the bridge itself though.
