### ISSUE TITLE
Synapse broken when bridges activated

### ISSUE THREAD

**Issue by timo95** [spantaleev/matrix-docker-ansible-deploy#192]
It tries to read `/matrix-mautrix-telegram-registration.yaml`, but there is only `/matrix/mautrix-telegram/registration.yaml`. The same is true for all bridges.

**Comment by spantaleev** [comment]
I was worrying that 70487061f introduced a regression, but I've just checked by using this configuration:

```yaml
matrix_mautrix_telegram_enabled: true
matrix_mautrix_telegram_api_id: YOUR_TELEGRAM_APP_ID
matrix_mautrix_telegram_api_hash: YOUR_TELEGRAM_API_HASH
```

and re-running the playbook (`--tags=setup-mautrix-telegram,setup-synapse`)

--------

Here are [the tasks](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/70487061f4aa1113b01c7e0bb1d83df424015743/roles/matrix-bridge-mautrix-telegram/tasks/setup_install.yml#L81) that currently do the wiring between the Telegram bridge and Synapse.

On the host, the file is indeed at: `/matrix/mautrix-telegram/registration.yaml`.

As far as the `matrix-synapse` container is concerned, that same file is supposed to be mounted read-only at another path: `/matrix-mautrix-telegram-registration.yaml`.

Synapse's systemd service file (`/etc/systemd/system/matrix-synapse.service`) should contain a line like this which does the mounting:

```
--mount type=bind,src=/matrix/mautrix-telegram/registration.yaml,dst=/matrix-mautrix-telegram-registration.yaml,ro
```

Because Synapse can see the registration file at `/matrix-mautrix-telegram-registration.yaml`, we also update `/matrix/synapse/config/homeserver.yaml` with an appservice registration like this:

```
app_service_config_files: ['/matrix-mautrix-telegram-registration.yaml']
```

----

It looks okay to me. I haven't tested this yet, nor can I test it correctly, because I don't normally use any bridges.

If you think there's a bug, I'd be happy to hear your feedback and fix it!

**Comment by timo95** [comment]
The mounting works, but it couldn't find the yaml:
```
FileNotFoundError: [Errno 2] No such file or directory: "u'/matrix-mautrix-telegram-registration.yaml'"
```
Changing the `/matrix/synapse/config/homeserver.yaml`
```
app_service_config_files: [u'/matrix-mautrix-telegram-registration.yaml', u'/matrix-mautrix-whatsapp-registration.yaml']
```
to this fixed it:
```
app_service_config_files: ['/matrix-mautrix-telegram-registration.yaml', '/matrix-mautrix-whatsapp-registration.yaml']
```

**Comment by spantaleev** [comment]
The problem seems to be that there's some `u` (unicode string) prefix that's making its way to the YAML.

I cannot reproduce this with:
- Ansible 2.8 on Python 3.7.3
- targeting Python 2.7.5 on the server

Can you share the output of `ansible-playbook --version` (where you run the playbook) and `python --version` (on the server)?

Maybe you are running Python 3 on the server?

----

I wonder if it would help to change `roles/matrix-synapse/templates/synapse/homeserver.yaml.j2` from:

```
app_service_config_files: {{ matrix_synapse_app_service_config_files }}
```

to:

```
app_service_config_files: {{ matrix_synapse_app_service_config_files|to_json }}
```

I've made such a fix in 2982b03. See if that solves the problem.

**Comment by timo95** [comment]
It works now.
```
app_service_config_files: ["/matrix-mautrix-telegram-registration.yaml", "/matrix-mautrix-whatsapp-registration.yaml"]
```

I run ansible on the server
```
ansible-playbook 2.8.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
```
and deploy it locally on the same server
```
Python 2.7.13
```
```
Description:    Debian GNU/Linux 9.9 (stretch)
```

**Comment by spantaleev** [comment]
Interesting!

No Python 3 involved anywhere, yet it likes serializing with a `u` prefix.

Thanks for finding and reporting this unfortunate regression! :+1:
