### ISSUE TITLE
Jitsi Video Stopped Working After Update

### ISSUE THREAD

**Issue by this-user** [spantaleev/matrix-docker-ansible-deploy#2025]
After updating Jitsi from 7577 to 7648, video and screen sharing consistently no longer works, and a blank screen is being shown to other participants on the call regardless of which client is being used. Audio works fine as does everything else. The only issue is the lack of video.

This used to work perfectly fine with previous versions. No configuration changes were made, and rolling back to 7577-2 restores the functionality.

This seems to be an issue with upstream, but I couldn't find anything in their changelog that would be an obvious candidate for causing this. Neither did I find anything about changes in the configuration that would be required to make video work with the updated version.

**Comment by etkecc** [comment]
Somehow similar: https://github.com/jitsi/jitsi-meet/issues/12026

**Comment by this-user** [comment]
Seems like it, except I just did a test and contrary to what one of the comments in that issue states, the problem does not occur if only Chromium clients are on the call. But as soon as one Firefox client joins, the shares screen turns blank. Even if it is only FF clients on the call, screen sharing does not work. 

So it seems like it has something to do with FF, which has always been a bit problematic with Jitsi.

**Comment by this-user** [comment]
So the issue seems to lie with the JVB "multi stream" feature. This is now enabled by default by upstream, but is disabled by default by this playbook. Enabling it fixes the aforementioned issue. Given that this is now their default, it might make sense to do the same in the playbook. See the following patch:

```
diff --git a/roles/matrix-jitsi/templates/jvb/env.j2 b/roles/matrix-jitsi/templates/jvb/env.j2
index 41d343b3..c17e49f7 100644
--- a/roles/matrix-jitsi/templates/jvb/env.j2
+++ b/roles/matrix-jitsi/templates/jvb/env.j2
@@ -1,6 +1,7 @@
 DOCKER_HOST_ADDRESS
 ENABLE_COLIBRI_WEBSOCKET
 ENABLE_OCTO
+ENABLE_MULTI_STREAM=true
 JVB_AUTH_USER={{ matrix_jitsi_jvb_auth_user }}
 JVB_AUTH_PASSWORD={{ matrix_jitsi_jvb_auth_password }}
 JVB_BREWERY_MUC={{ matrix_jitsi_jvb_brewery_muc }}
```

**Comment by spantaleev** [comment]
Interestingly, as of the current latest master (`eb0dd6b0653a91`):

- `ENABLE_MULTI_STREAM` defauilts to `true` for the `web` component: https://github.com/jitsi/docker-jitsi-meet/blob/eb0dd6b0653a9144de8f75c8c0f8a8560e04abef/web/rootfs/defaults/settings-config.js#L24
- `ENABLE_MULTI_STREAM` defaults to `false` for the `jvb` component: https://github.com/jitsi/docker-jitsi-meet/blob/eb0dd6b0653a9144de8f75c8c0f8a8560e04abef/jvb/rootfs/defaults/jvb.conf#L4
- `ENABLE_MULTI_STREAM` is not specified at all in [`.env.example`](https://github.com/jitsi/docker-jitsi-meet/blob/eb0dd6b0653a9144de8f75c8c0f8a8560e04abef/env.example). So I'm not sure how we can claim that it's enabled by default in upstream. Unless I'm missing something, upstream:
    - doesn't list this environment variable at all in their example configuration (it only mentions it in [`docker-compose.yml`](https://github.com/jitsi/docker-jitsi-meet/blob/eb0dd6b0653a9144de8f75c8c0f8a8560e04abef/docker-compose.yml)
    - uses different defaults for its different components (`web` and `jvb`) when it comes to this variable
- Jitsi configuration seems to be mixing boolean (true/false) and numeric (0/1) values - other bool variables in [web/rootfs/defaults/settings-config.js](https://github.com/jitsi/docker-jitsi-meet/blob/eb0dd6b0653a9144de8f75c8c0f8a8560e04abef/web/rootfs/defaults/settings-config.js) favor `default "true"` and `default "false"`, instead of `default "1"` and `default "0"`. It probably doesn't matter because ` | toBool` makes it all a bolean in the end, but.. weird inconsistency
- some bug related to multi-stream is [supposedly fixed](https://github.com/jitsi/docker-jitsi-meet/commit/eb0dd6b0653a9144de8f75c8c0f8a8560e04abef)

The following upstream issue may be relevant: https://github.com/jitsi/docker-jitsi-meet/issues/1370

**Comment by this-user** [comment]
I only enabled it in the JVB config, which did solve the problem. This was disabled without setting the env variable. One can verify that it is enabled in the jvb.conf that the Docker image generates in its data directory.

The did claim that MS is enabled by default, but that's definitely not the case for the JVB Docker image. However, it does seem to be enabled in their[ default configuration file](https://github.com/jitsi/jitsi-videobridge/blob/master/jvb/src/main/resources/reference.conf) for the non-Docker version. I think that maybe that's what they are referring to, but they simply forgot to change it for the Docker image where it still defaults to 'false'.

**Comment by this-user** [comment]
They have released a new version [stable-7648-1](https://github.com/jitsi/docker-jitsi-meet/releases/tag/stable-7648-1). I have tested that one, and it seems to work without issue now.
