### ISSUE TITLE
Can't startup the dimension servcie

### ISSUE THREAD

**Issue by elohffa** [spantaleev/matrix-docker-ansible-deploy#211]
When I add to enable the dimension service in my vars.yml
matrix_dimension_enabled: true
matrix_dimension_admins: ['@dimension_admins:domain.com']
matrix_dimension_access_token: "My access token for @dimension_admins "

When I shoot the command : ansible-playbook -i inventory/hosts setup.yml --tags=start

then I got this error : failed: [matrix.sanaipin.com] (item=matrix-dimension) => {"ansible_loop_var": "item", "changed": false, "item": "matrix-dimension", "msg": "matrix-dimension was not detected to be running. It's possible that there's a configuration problem or another service on your server interferes with it (uses the same ports, etc.). Try running `systemctl status matrix-dimension` and `journalctl -fu matrix-dimension` on the server to investigate."}

When I shoot command journalctl -fu matrix-dimension , it report me the token is incorrect 
body: '{"errcode":"M_UNKNOWN_TOKEN","error":"Invalid macaroon passed."}' }

**Comment by sbutler-gh** [comment]
Hi @elohffa. I'm getting a similar error (for me,`"item": matrix-dimension.service` instead of `"item": "matrix-dimension"`)

` {"ansible_loop_var": "item", "changed": false, "item": "matrix-dimensio.servicen", "msg": "matrix-dimension .servicewas not detected to be running. It's possible that there's a configuration problem or another service on your server interferes with it (uses the same ports, etc.). Try running systemctl status matrix-dimension.service and journalctl -fu matrix-dimension.service on the server to investigate."}`

{"errcode":"M_UNKNOWN_TOKEN","error":"Invalid macaroon passed."}' 

Did you find a fix for this?

**Comment by sbutler-gh** [comment]
Update:

In my case, the issue was an incorrect `matrix_dimension_access_token` (I hadn't copied the entire token block from my dimension user on element.BASE_DOMAIN)

After pasting the correct token for `matrix_dimension_access_token` in vars.yml, I ran `--tags=stop`, then `--tags=setup-all,start`, and the playbook ran successfully without any failures or errors
