### ISSUE TITLE
matrix-ntfy failed to start

### ISSUE THREAD

**Issue by NewOcean11** [spantaleev/matrix-docker-ansible-deploy#2188]
**Describe the bug**
2022/10/22 04:55:58 INFO Listening on :80[http], ntfy 1.28.0, log level is DEBUG
2022/10/22 04:55:58 listen tcp :80: bind: permission denied
matrix-ntfy.service: main process exited, code=exited, status=1/FAILURE
Unit matrix-ntfy.service entered failed state.
matrix-ntfy.service failed.

try to listen @ port 80 but denied，why？
need I to set another port?

**Comment by spantaleev** [comment]
It looks like we're using a regular user to start it and are dropping all capabilities: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/782407cf89054ddb59213cf1d4038af08362f197/roles/matrix-ntfy/templates/systemd/matrix-ntfy.service.j2#L16-L18

.. so it does make sense that it would fail to bind on port `80` inside the container.

This should hopefully be fixed by 57bb340343c692c9439c8, although I haven't tested it. Please confirm!

**Comment by NewOcean11** [comment]
> It looks like we're using a regular user to start it and are dropping all capabilities:
> 
> https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/782407cf89054ddb59213cf1d4038af08362f197/roles/matrix-ntfy/templates/systemd/matrix-ntfy.service.j2#L16-L18
> 
> .. so it does make sense that it would fail to bind on port `80` inside the container.
> 
> This should hopefully be fixed by [57bb340](https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/57bb340343c692c9439c863cd1d13c54cecb87b8), although I haven't tested it. Please confirm!

no fixed,and cause matrix-nginx-proxy failed,u must have a try bt ur self
