### ISSUE TITLE
Upgrading services using Ansible via Docker with some issues

### ISSUE THREAD

**Issue by krassle** [spantaleev/matrix-docker-ansible-deploy#2248]
**Describe the bug**

Following [Upgrading the Matrix services](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/maintenance-upgrading-services.md#upgrading-the-matrix-services) using Ansible via Docker leads to some issues.

1. Running `make roles` in the container returns: `/bin/sh: make: not found`
2. Manually running the commands from the `Makefile` fails at the last command: `/bin/sh: ansible-lint: not found`
3. Re-running the playbook setup returns one failed TASK (See LOG below):
 - `/work # ansible-playbook -i inventory/hosts setup.yml --tags=setup-all,ensure-matrix-users-created,start`
4. Running `git config --global --add safe.directory /work` and repeating step 3 is what finally solved the issue

**Ansible-playbook setup LOG**
```log
[...]
TASK [galaxy/com.devture.ansible.role.playbook_state_preserver : Fail if required playbook-state-preserver settings not defined] **********************************************************************************
skipping: [matrix.redacted.com] => (item=devture_playbook_state_preserver_uid) 
skipping: [matrix.redacted.com] => (item=devture_playbook_state_preserver_gid) 

TASK [galaxy/com.devture.ansible.role.playbook_state_preserver : Fail if required playbook-state-preserver vars.yml-preservation settings not defined] ************************************************************
skipping: [matrix.redacted.com] => (item=devture_playbook_state_preserver_vars_preservation_dst) 

TASK [galaxy/com.devture.ansible.role.playbook_state_preserver : Preserve vars.yml on the server for easily restoring if it gets lost later on] *******************************************************************
ok: [matrix.redacted.com]

TASK [galaxy/com.devture.ansible.role.playbook_state_preserver : Fail if required playbook-state-preserver commit-hash-preservation settings not defined] *********************************************************
skipping: [matrix.redacted.com] => (item=devture_playbook_state_preserver_commit_hash_preservation_dst) 

TASK [galaxy/com.devture.ansible.role.playbook_state_preserver : Get local git hash] ******************************************************************************************************************************
fatal: [matrix.redacted.com -> 127.0.0.1]: FAILED! => changed=false 
  cmd: git describe --always --tags --dirty --long --all
  delta: '0:00:00.010681'
  end: '2022-11-08 21:34:27.186078'
  msg: non-zero return code
  rc: 128
  start: '2022-11-08 21:34:27.175397'
  stderr: |-
    fatal: unsafe repository ('/work' is owned by someone else)
    To add an exception for this directory, call:
  
            git config --global --add safe.directory /work
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>

TASK [galaxy/com.devture.ansible.role.playbook_state_preserver : Inject git not found warning] ********************************************************************************************************************
skipping: [matrix.redacted.com]

TASK [galaxy/com.devture.ansible.role.playbook_state_preserver : Get GIT hash error] ******************************************************************************************************************************
fatal: [matrix.redacted.com]: FAILED! => changed=false 
  msg: 'Error when trying to get the git hash. Please consult the error message above. You can disable saving the commit hash by setting ''devture_playbook_state_preserver_commit_hash_preservation_enabled: false'' in vars.yml'

PLAY RECAP ********************************************************************************************************************************************************************************************************
matrix.redacted.com         : ok=259  changed=10   unreachable=0    failed=1    skipped=2038 rescued=1    ignored=0
```

**Expected behavior**
Upgrade goes without issues and with less copy-paste :) 

**Matrix Server:**
 - OS: Ubuntu 20.04
 - Architecture: arm64

**Ansible:**
Running Ansible in a container on the Matrix server itself [docker.io/devture/ansible:2.13.0-r0]

**Additional context**

**Comment by spantaleev** [comment]
Thank you for this detailed report (containing multiple important issues)!

----

The new `2.13.6-r0` tag of `devture/ansible` now contains the `make` utility, so `make roles` should work.

----

As for running the `make` commands manually, you're only expected to run the commands under `roles` only. Running any other commands (those for `lint`, etc.) is not necessary, unless you're doing new developments on the playbook.

Hopefully the change in 32e5c814e48293048 makes it clearer that you're note expected to run `ansible-lint` or anything else in the container.

While I could add `ansible-lint` to the `devture/ansible` container image, doing that makes the container image size larger for no good reason (most people don't need it).

---

The other issue is that `git` fails to work locally because the playbook directory is owned by *you* (a regular user) outside of the container, but you're operating as `root` inside of the container.

I've added your workaround to `docs/ansible.md` in 06df2df9e90fd09ac50fcab3f88c85fea5116dae

---

With that, I believe we should be back to being able to run Ansible in a container smoothly.
