### ISSUE TITLE
Element Changed its dockerfile, can no longer compile on ARM (Ensure Element Docker image is built)

### ISSUE THREAD

**Issue by AIndoria** [spantaleev/matrix-docker-ansible-deploy#2318]
I am trying to run the playbook on ARM64, Ubuntu 20.10 (Ansible is appropriately updated).

**What happened:**

Element pushed a breaking change:

https://github.com/vector-im/element-web/commit/3366ed1af0971f18c552a45f823eb9c16e1334ef

That changes

`FROM node:16-buster as builder`

to

`FROM --platform=$BUILDPLATFORM node:16-buster as builder`

Thus, element self builds on ARM platforms no longer work.

In  https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/roles/custom/matrix-client-element/tasks/setup_install.yml#L52

adding 

`platform: linux/arm64 `or `arm64 `does not work. Nor does adding `args `under `build `parameter, as per the Ansible documentation here:

https://docs.ansible.com/ansible/latest/collections/community/docker/docker_image_module.html#parameter-build/platform

The error given is the following:

```
FAILED! => changed=false
  msg: 'Error building localhost/vectorim/element-web - code: None, message: failed to parse platform : "" is an invalid component of "": platform specifier component must match "^[A-Za-z0-9_-]+$": invalid argument, logs: [''Step 1/17 : FROM --platform=$BUILDPLATFORM node:16-buster as builder'', '''']'
```

**Comment by spantaleev** [comment]
Looks like we need to use `docker buildx` now, so that it would correctly pass the `BUILDPLATFORM` argument - https://docs.docker.com/build/building/multi-platform/

---

Our self-building was indeed broken, but.. we're not supposed to be using self-building on `arm64`, so it shouldn't have affected most people on ARM64. Element already offers pre-built images for `arm64` and the playbook is supposed to make use of them, instead of building by itself.

This should have only been affecting people on architectures other than `amd64` and `arm64` (such as `arm32`), or people who have explicitly enabled self-building (`matrix_client_element_container_image_self_build: true`) for some reason.

In any case, I've fixed this in b2a40effaf2451afff8
