### ISSUE TITLE
Matrix Federation Tester failing with SRV record - invalid character "<"

### ISSUE THREAD

**Issue by dacruz21** [spantaleev/matrix-docker-ansible-deploy#241]
I am attempting to register my homeserver at matrix.typokign.com to be authoritative for typokign.com, but I don't have access to serve the .well-known files on typokign.com. Instead, I'm trying to go about the SRV record route, but am running into issues.

I created the `_matrix-identity._tcp 10 0 443 matrix.typokign.com` record on my domain, then ran the [Matrix Federation Tester](https://federationtester.matrix.org/api/report?server_name=typokign.com) to verify the record. Instead, I got an error that the `_matrix._tcp` record did not exist (this record was not mentioned anywhere in the docs), so I created the record. Now, the federation tester is resolving my host, but I am getting this message in the ConnectionErrors: `Unable to decode JSON from remote server: invalid character '<' looking for beginning of value`.

I'm not sure what route the federation tester is trying to call, or why my homeserver is returning an invalid response. I am happy to manually poke at routes if someone knows what I should be trying.

Thanks!

**Comment by spantaleev** [comment]
I'm not sure what code-path the Matrix Federation Tester is taking and why it's failing. 
Consider opening an issue on [the repository for their backend](https://github.com/matrix-org/matrix-federation-tester) to urge them to make this error message be more helpful.

Regardless of this, I can give you some pointers about what you're trying to do.

You seem to have delegated to `matrix.typokign.com:443` and not to the usual federation port (`8448`).

Delegating via a SRV record (regardless of which port you delegate to) requires that the server you delegate to satisfies the following things:
- serves HTTPS traffic on the specified port :heavy_check_mark: 
- serves federation HTTPS traffic **using a certificate for the delegating domain (typokign.com)**, and not for its own domain (matrix.typokign.com) :o:
- serves federation endpoints over the specified port (in your case `https://matrix.typokign.com/_matrix/federation/v1/version`) :o:

Your server fails to satisfy the last 2 requirements.

Besides the above "federation requirements", you also probably wish to satisfy client-server requirements, so that Matrix clients can talk to your Matrix server. Those clients will typically want traffic going to `matrix.typokign.com` to use a certificate valid for `matrix.typokign.com`. So, should you switch the certificate to one for `typokign.com` only, you'll fix federation requirement 2 above, but you'll break client-server requirements. You will need a certificate valid for **both** domains (`typokign.com` and `matrix.typokign.com`).

For fixing federation requirement 3, I think you'll just have to abandon using port 443.
The playbook does not provide controls for helping you "enable serving federation traffic on the non-federation port".

So, my advice is:
- don't go for delegation using SRV records. They're usually a pain to deal with, as you can see. If you definitely can't arrange to have access to the base domain (`typokign.com`), then obviously this advice is useless.
- if you really need to delegate using SRV records, at least:
  * don't delegate to port 443. Delegate to port 8448 instead
  * obtain an SSL certificate valid at least for both `typokign.com` and `matrix.typokign.com`. If you throw in `riot.typokign.com`, that'd be better. A wildcard certificate for `typokign.com` works as well.
  * use [manually-managed SSL certificate retrieval](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-ssl-certificates.md#using-your-own-ssl-certificates)
- if all of the above is too complicated or impossible, consider not using domain delegation at all. Just use `matrix.typokign.com` as your Matrix domain and remove your SRV records. User and room ids are uglier, but it's a simple setup. You just need to set these variables:
  * `matrix_domain: typokign.com`
  * `matrix_server_fqn_matrix: {{ matrix_domain }}`
  * `matrix_server_fqn_riot: {{ matrix_domain }}`
  * `matrix_server_fqn_dimension: {{ matrix_domain }}` (maybe you don't use Dimension, but it doesn't hurt to set this too)

If you need more pointers with any of these, consider [joining our Support room](https://github.com/spantaleev/matrix-docker-ansible-deploy#support) using another Matrix account or using IRC.
