### ISSUE TITLE
Etherpad standalone letsencrypt not renewing after standalone reinstall

### ISSUE THREAD

**Issue by joecool1029** [spantaleev/matrix-docker-ansible-deploy#2447]
Background
- Previously used Etherpad with Dimension
- Once standalone support was announced and set to default, accidentally upgraded and issued cert for it.
- Reverted to use Etherpad with Dimension again, let Etherpad cert expire.
- Intentionally removed Dimension, configured to use standalone Etherpad.

Problem
- Standalone Etherpad currently serving the expired SSL cert from last year.
- Running  /matrix/ssl/bin/lets-encrypt-certificates-renew directly doesn't show etherpad in the list of domains.

**Comment by spantaleev** [comment]
As discussed on our Matrix support room, the problem is that.. disabling a service causes the playbook to delete the renewal `.conf` file for Certbot, so that it wouldn't try to renew this (now unnecessary) certificate over and over in the future. If we didn't do this (as was the case before we implemented it in 9c549a185f6b035cb), then it was either renewing a certificate you don't need.. or it was failing to renew it (if you had dropped the DNS record) and you'd be getting an email from Let's Encrypt telling you about it and it and necessitating manual cleanup work.

------

The problem is that.. the certificate files are still there for this old domain in `/matrix/ssl/config/live`.. So when you enable the domain again in the future, the playbook says "oh, I have this certificate already.. nothing to do" and doesn't invoke Certbot. Given that it's not invoking certbot, then certbot doesn't set up "renewal" and renewal will never happen. In addition, it's possible that the SSL certificate had expired already, which is **another** related problem.

-----

I suppose we could improve the purging part, so that it also deletes the certificate files for the disabled service. Doing that, reenabling it later would retrieve a new certificate and set up new renewal files.

----

Another solution is for the playbook to detect the missing renewal `.conf` files during setup and try to recreate them somehow.

----

A third solution.. is to switch to Traefik and drop the whole nginx + certbot mess.

This is what I'm working on right now (for other reasons, not to fix this current issues). Once we switch, this problem will go away on its own, because certificates will be managed by Traefik.

**Comment by joecool1029** [comment]
I got up and going again just looking for anything named *etherpad* in /matrix/ssl and rm'ing it. 

> I suppose we could improve the purging part, so that it also deletes the certificate files for the disabled service. Doing that, reenabling it later would retrieve a new certificate and set up new renewal files.

This makes sense to do, it might actually make sense to revoke the certificates if a service is removed, avoids future expiration emails from letsencrypt. Then purge the certs and the configs to get back to a clean slate.

> Another solution is for the playbook to detect the missing renewal .conf files during setup and try to recreate them somehow.

Added complexity to handle the mess left behind. Better to just clean up when we are done and not leave the mess in the first place.

> A third solution.. is to switch to Traefik and drop the whole nginx + certbot mess.

All for it if it's less flaky.
