### ISSUE TITLE
IOS ringtone in Matrix Synapse installed using ansible?

### ISSUE THREAD

**Issue by a19901201** [spantaleev/matrix-docker-ansible-deploy#2469]
I have installed Matrix Synapse and Sygnal using this deployment script: https://github.com/spantaleev/matrix-docker-ansible-deploy but I am unable to figure out how to set the IOS ringtone.

I have tried the following configuration in the Sygnal configuration file, but it doesn't seem to work:
```

data:
  default_payload:
    aps
      sound:"ring.mp3"

data:
  default_payload:
    aps
      sound:"ring"

data:
  default_payload:
    aps:
      sound:"ring"

data:
  default_payload:
    aps:
      sound:"ring.mp3"

data:
  default_payload:
    aps:
      sound:ring.mp3

default_payload:["aps":["sound":"ring.mp3"]]

default_payload:["aps":{"sound":"ring.mp3"}]

default_payload:["aps":{"sound":"ring"}]

default_payload:["aps":["sound":"ring"]]

data:
  default_payload:
    aps:
      ["sound":"ring"]

data:
  default_payload:
    aps:
      {"sound":"ring"}

```

I have "Sounds/ring.mp3" in my APP
If you have any knowledge on how to resolve this issue, please help me out. Thank you!

**Comment by spantaleev** [comment]
This doesn't seem to have anything to do with the deployment method.

Why are you not opening this issue in the [Sygnal repository](https://github.com/matrix-org/sygnal) or the [element-ios repository](https://github.com/vector-im/element-ios/)?

**Comment by a19901201** [comment]
I have asked related questions multiple times in Sygnal repository, Sygnal and Matrix communities, but have never received any response. Only some people told me not to ask questions there and redirect me to other places. Each place asks me to go somewhere else to ask questions. Moreover, some other users even directly told me that asking questions in these places would not be helpful, and that I should try to solve problems myself. This has made me very frustrated. I have been building Matrix for more than six months, almost relying on try and error. I also hope to provide some amount of money to get paid help, but still without any results.

**Comment by spantaleev** [comment]
Well, we're just a deployment mechanism.. If Sygnal starts, then our job is done.

The fact that Element would not play some mp3 may be a problem with Element not being connected to Sygnal (have you pointed your app to your custom Sygnal server?), or Sygnal not providing that configuration.

The latter can indicate that our deployment doesn't work and is providing you with a broken Sygnal. Or.. it could mean that your Sygnal configuration is wrong.. or you're not putting it in the right place (check configuration file indentantion, etc.).

Most likely, the problem is not with the deployment method, but with Element or Sygnal. It's sad to hear that you're not getting good help at those repositories. Sygnal is rarely used by anyone, so it's hard to find decent help. I've also never used it myself. element-ios is known to be the worst app in existence, so something not working on it is to be expected. Hopefully, you'll find some workaround

**Comment by a19901201** [comment]
Thank you very much for your response. I understand that sygnal is not commonly used, and I appreciate you telling me about the element-ios. I will try to find another solution to my problem. Thank you again.
