### ISSUE TITLE
Add support for spam filtering

### ISSUE THREAD

**Issue by ptman** [spantaleev/matrix-docker-ansible-deploy#255]
https://github.com/t2bot/synapse-simple-antispam ?

**Comment by spantaleev** [comment]
This could probably be implemented like we've done it for other extensions (password providers). That is:

- there are additional playbook tasks in the `roles/matrix-synapse/tasks/ext` directory
- instead of fetching a single file with the `get_url` Ansible module, we'd probably need to clone the whole git repository, because `synapse-simple-antispam` seems to be a Python module with an `__init__.py` file (or maybe we can work around that)
- we'd need to use `matrix_synapse_container_extra_arguments` to mount the Python file (or module) to where Synapse would find it (`matrix_synapse_in_container_python_packages_path`)
- we'd need a new variable for `spam_checker`, which we override with the relevant configuration if `synapse-simple-antispam` is enabled in our configuration

**Comment by spantaleev** [comment]
Due to the large interest in this, I've went ahead and implemented it.
Thanks for bringing it up!

**Comment by ptman** [comment]
Np, thanks for implementing it.
