### ISSUE TITLE
Add `recurse: yes` in "Ensure Postgres paths exist"

### ISSUE THREAD

**Issue by liquidat** [spantaleev/matrix-docker-ansible-deploy#257]
The task "[Ensure Postgres paths exist](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/a6d51ebe9b10c410b20ed1ce63a8e29481c6e9b1/roles/matrix-postgres/tasks/setup_postgres.yml#L41)" should not only change the ownership of the main path, but also of containing files and directories. Otherwise there might be ownership problems when starting the containers.

**Comment by spantaleev** [comment]
This only happens if you're moving files from some other existing installation and you don't chown them properly, right?

Under normal circumstances it shouldn't be necessary to do it recursively. The main directory is created with the right user (`matrix`) and Postgres is then launched with the user, thus making all files owned by `matrix`.

I guess it doesn't hurt to do it recursively though. Right now, we create a few environment variables files under the base path `matrix_postgres_base_path` (`/matrix/postgres`) which are owned by `root`. If we are to add `recurse: yes` to "Ensure Postgres paths exist", we'd be chowning those files as well, reporting that something **changed**.

The "Ensure Postgres environment variables file created" task after that would chown those environment variable files to `root` again, reporting yet another **change**.

We either need to let go and have these files owned by `root`, or (probably) better yet make the `recurse: yes` thing apply only to the Postgres data directory (`matrix_postgres_data_path`) and not the base directory (`matrix_postgres_base_path`).

**Comment by liquidat** [comment]
> This only happens if you're moving files from some other existing installation and you don't chown them properly, right?

That's what I would expect, yes. Though tbh I stumbled upon on this when I freshly formatted the data path. I yet have to investigate what went wrong.

> I guess it doesn't hurt to do it recursively though.

That was the intention of this issue, yes. Might as well do this for all data path subdirectories, maybe? To be consistent?

> Right now, we create a few environment variables files under the base path `matrix_postgres_base_path` (`/matrix/postgres`) which are owned by `root`. If we are to add `recurse: yes` to "Ensure Postgres paths exist", we'd be chowning those files as well, reporting that something **changed**.
> The "Ensure Postgres environment variables file created" task after that would chown those environment variable files to `root` again, reporting yet another **change**.

Ah, I wasn't fully aware of this. You would always have a change.

> We either need to let go and have these files owned by `root`, or (probably) better yet make the `recurse: yes` thing apply only to the Postgres data directory (`matrix_postgres_data_path`) and not the base directory (`matrix_postgres_base_path`).

The second idea sounds like a reasonable change - actually something a DB admin would expect - without breaking existing workflows too much - aka the root owned files.

Thanks for taking so much time for the answer!

**Comment by spantaleev** [comment]
This is now implemented! Thanks for suggesting this improvement! :+1:

**Comment by liquidat** [comment]
I thank you for accepting it!
And thanks for the project in general, it really helped me getting my first Matrix server up and running :)
