### ISSUE TITLE
Sydent Identity Server?

### ISSUE THREAD

**Issue by eMPee584** [spantaleev/matrix-docker-ansible-deploy#288]
Has anyone as of yet looked into supporting sydent? Would it make sense to support it, given recent privacy changes to synapse and riot, and with regard to mxisd's zombie state?
Seems to have become quite alive recently (https://github.com/matrix-org/sydent/graphs/contributors), although I remember to have read somewhere it is really not supposed to be used by anyone except matrix.org...

**Comment by Metzlmane** [comment]
I'd also support this.
mxisd got forked by ma1sd which is working very well

**Comment by spantaleev** [comment]
Unless someone sees a good reason and wants to work on this, we probably don't have a need for it, now that we have ma1sd (via #333).

**Comment by red0888** [comment]
Don't wanna necropost but msxid is discontinued-ish and would be nice if sydent gets integrated...

**Comment by luixxiul** [comment]
I'd like to reopen in case someone will work on it :crossed_fingers:

**Comment by christophwolff** [comment]
Iam very interrested in this, too

**Comment by BohdanK-W32** [comment]
Well, I guess it's the only way to support such functionality right now

**Comment by Garretby** [comment]
Any news? Since ma1sd has been deprecated, this is the only remaining solution.

**Comment by spantaleev** [comment]
Closing this again, with apologies to those still waiting on it.

This is not a dead-upstream close: Sydent is alive and maintained at element-hq/sydent, with an official container image (matrixdotorg/sydent). It is a demand-versus-effort one. Identity servers have been de-emphasized in the Matrix ecosystem for years (their main uses, third-party identifier lookup and invites by email or phone, are niche), and the playbook dropping ma1sd as unmaintained caused little fallout. This request has been open since 2019 and was reopened once in the hope that someone would work on it, but in all that time nobody has stepped up to build and maintain the integration. Keeping it open would keep signaling a promise nobody is working on.

If you need Sydent today, it can be self-hosted next to the playbook using the official matrixdotorg/sydent image. If a contributor wants to champion a proper integration (the existing roles make good templates and the official image makes it a well-trodden path), a pull request is very welcome and this can be revived.
