### ISSUE TITLE
Make use of releases

### ISSUE THREAD

**Issue by CybotTM** [spantaleev/matrix-docker-ansible-deploy#292]
Hi,

first, thanks for all your work you put into this here.
Helped us a lot to start and maintain our own Matrix service.

Could you please consider making use of the release feature within GitHub?

So user can more easily get notified about feature changes, by watching releases for this project.

![image](https://user-images.githubusercontent.com/326348/68010758-c5269200-fc85-11e9-959e-c349b6921b78.png)

Would appreciate it.
Thanks a lot.

**Comment by aaronraimist** [comment]
Every commit changes something. If you want a reminder to update, you could watch the Synapse repo.

**Comment by CybotTM** [comment]
Hi @aaronraimist ,

thanks for your reply.

> Every commit changes something.

Of course, that's the meaning of a commit - a change, isn't it? ;-)

> If you want a reminder to update, you could watch the Synapse repo.

But this repo is doing more than just installing Synapse, there are more services involved, and set up, changes without a new Synapse version, changes on other modules, changes in set up - maybe even security related ones, a.s.o.

**Comment by spantaleev** [comment]
We've discussed this many times with various people (in the support room, etc.).

The general consensus seems to be that:
- due to having so many components that need upgrading, things move too fast and tagging releases would be quite random.
- many of our components use a `:latest` Docker image, because they don't provide a proper tagged release. Even if we try tagging some releases, you're never guaranteed to get exactly the same thing.
- we very rarely break compatibility these days, so we'll mostly be bumping up the minor version number a lot.. It will quickly get boring doing that.

If someone every has a better proposal, let's discuss it again, either here or by chatting in the support room.

**Comment by CybotTM** [comment]
ok, thanks for your answer.

Just some final notes:

* You already have a Changelog - entries looks like releases to me.
* Release doesn't need to have semantic versioning - you can go with ISO formatted dates as in the Changelog
* You are not releasing (versioning) the containers you are using (latest) but the recipe/configcode to run/deploy them

But i understand your point - and of course it's an additional effort.
Thanks.
