### ISSUE TITLE
Is it possible to set up everything on a subdomain?

### ISSUE THREAD

**Issue by lord-ne** [spantaleev/matrix-docker-ansible-deploy#3103]
If I have a domain `bar.com` which is being used for other things (and I'm not able to set up reverse proxy), can I just set up this whole playbook on a subdomain `foo.bar.com`? So this server would have subdomains `matrix.foo.bar.com`, `element.foo.bar.com`, etc, and users would have identifiers like `@<username>:foo.bar.com`.

I would imagine this should work, but since there was a lot of emphasis in the documentation on workarounds you have to do for the `.well_known` files if you're using the main domain for something else, when just using a subdomain seems like a much simpler solution for many people, that I was wondering if there is perhaps some reason that this doesn't work?

**Comment by spantaleev** [comment]
Yes.

With a configuration like `matrix_domain: foo.bar.com`, your base domain would become `foo.bar.com` and all services would be on subdomains (e.g. `matrix.foo.bar.com`, `element.foo.bar.com`). You don't to override any other hostnames to have it work this way - just set `matrix_domain` to the base domain you'd like to use and it would cascade to all other variables handling the other domain names.

Since your Matrix server would be on `matrix.foo.bar.com`, while the base domain is different (`foo.bar.com`), you'd still need to do delegation via `/.well-known/matrix/server`. If you've pointed `foo.bar.com` to the Matrix server, you can tell the playbook to [handle the base domain domain](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-base-domain-serving.md) for you with this configuration: `matrix_static_files_container_labels_base_domain_enabled: true`.

-----

That said, some people wish to use `matrix.example.com` as their base domain and **also** for their Matrix domain.
That is, all they'd like to have is `matrix.example.com` - both in their usernames (`@<username>:matrix.example.com`) and for the server's domain name. In your case, it could be `foo.bar.com`, instead of `matrix.example.com`.

Then, they'd also like to use custom domains for things like Element (e.g. `element.example.com`  instead of `element.matrix.example.com`).

As mentioned above, services get subdomains (relative to `matrix_domain`) by default, so uch people can set a few more variables to override these defaults:

```yml
matrix_domain: matrix.example.com

# Overriding this to avoid it becoming matrix.matrix.example.com
matrix_server_fqn_matrix: matrix.example.com

# Overriding this to avoid it becoming element.matrix.example.com
matrix_server_fqn_element: element.example.com
```

When your base domain (`matrix_domain`) matches the domain of the Matrix server (`matrix_server_fqn_matrix`) you **don't** need to do anything for (well-known) delegation. The Matrix server handles it by itself.
