### ISSUE TITLE
Playbook adds docker repository even tho it shouldn't install docker

### ISSUE THREAD

**Issue by mwelsch** [spantaleev/matrix-docker-ansible-deploy#3170]
The playbook fails at `Add Docker repository` while running because for Debian trixie (testing). I specified in the `vars.yml` that I manage docker installation myself, as pointed out in the faq :

```
matrix_playbook_docker_installation_enabled: false
```
[Full vars - yaml (can only upload .txt here)](https://github.com/spantaleev/matrix-docker-ansible-deploy/files/14223685/vars.txt)

**How I reproduced the behavior**
Create a new diretory
Pull the newest github repo there
Add the `vars.yml` to the inventory
Edit the `hosts` file in the inventory
Run:
```
just roles
just setup-all
[...]
fatal: [redacted.pro]: FAILED! => changed=false 
  msg: 'Failed to update apt cache: E:The repository ''https://download.docker.com/linux/debian trixie Release'' does not have a Release file., W:Updating from such a repository can''t be done securely, and is therefore disabled by default., 
W:See apt-secure(8) manpage for repository creation and user configuration details., W:https://aquasecurity.github.io/trivy-repo/deb/dists/bullseye/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.'
```

In the [mash-playbook](https://github.com/mother-of-all-self-hosting/mash-playbook) setting the corresponding variable to false works and the playbook runs fine

**Comment by spantaleev** [comment]
This doesn't sound right. See: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/b91da76c6c4f9bf2d7af1a913cd1d7c1583594b3/setup.yml#L17-L26

Regardless, it wouldn't hurt to have both playbooks try to install Docker though. It's wasteful, but shouldn't cause any issues. Both playbooks would run the same exact code - the [geerlingguy/docker](https://github.com/geerlingguy/ansible-role-docker) Ansible role.

Your clipped log message does not tell us which task failed. Perhaps it's not part of the Docker installation, but of something else. The [playbook-help](https://github.com/devture/com.devture.ansible.role.playbook_help) Ansible role runs early on (before the Docker role) and warms up the apt cache, so that any role that may install packages later on could benefit from that. It's most likely that the playbook fails there.

Even without the playbook, you logging into the server and doing `apt update` would likely result in the same problem related to Debian legacy keys (bullseye) and trying to access some Docker apt repository as `trixie`.. It's likely that no such packages exist, but I don't know about that. Consider troubleshooting your apt sources and perhaps deleting the Docker one (likely added by MASH).

**Comment by mwelsch** [comment]
Thanks for the reference, I tried just deleting those line and now the playbook complains about `matrix_homeserver_generic_secret_key` beeing undefined. Something in my setup leads to my `vars.yml` not beeing read, guess I'll figure it out

**Comment by spantaleev** [comment]
`vars.yml` is most likely not being read, because the hostname in `inventory/hosts` has a typo.. Or the path `inventory/host_vars/HOSTNAME/vars.yml` has a typo. The hostname needs to be identical.
