### ISSUE TITLE
Migration to an new server. No user found 

### ISSUE THREAD

**Issue by Happyfeet01** [spantaleev/matrix-docker-ansible-deploy#3403]
Hello,

I used this Tutorial to migrate to an new server.  https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/maintenance-migrating.md
. It works, but it seems there is no user. 

Copied the /matrix folder also the /opt/matrix-ansible folder. Run the chown command. Then start the server.

import an database fails

`ERROR:  role "matrix_go_skype_bridge" already exists
    STATEMENT:  CREATE ROLE matrix_go_skype_bridge;
  stderr_lines: <omitted> `

Have I forgot something? 🤷🏼‍♂️🤔

**Comment by spantaleev** [comment]
Are you migrating to another CPU architecture?

If you **are migrating** to another CPU architecture: then you should sync all `/matrix` files with the exception of `/matrix/postgres/data`, as that `data` directory will not be usable on the new host. Doing this, you'll start with a fresh Postgres into which you can import a database from a dump file.

If you **are not migrating** to another CPU architecture: then there's no need to import the database from a dump file. Your migrated setup has a `/matrix/postgres/data`  directory, which is usable. Trying to import will result in the error you're stating.

I have tried to clarify this in 6c3746b23753c7c45fd6d33e83484eeff3a61630

-----

I suppose you:

- **are not migrating** to a host running another CPU architecture
- have synced all `/matrix` files, including the database data (`/matrix/postgres/data`)
- are now trying to import Postgres data from a dump on top of the already existing data

If you were migrating to another CPU architecture and have followed these steps, then you'd hit an error during Postgres startup (complaining about being unable to read the data). Since it's not complaining, then you are likely on the same CPU architecture. At which point, why import data at all?

----

Another reason someone may get an error like the one you're stating is if you:

- **are indeed migrating** to a host running another CPU architecture
- have synced all `/matrix` files, but have excluded the database data (`/matrix/postgres/data`) as expected
- against recommendations, you have started Matrix services here.. Which made them create some roles and databases.
- are now trying to import Postgres data from a dump on top of this already existing data

----

That said, something else may have happened and this may be a legit bug.

**Comment by Happyfeet01** [comment]
Hello,

Firstly, thank you for the detailed answer.  Both servers, the old and the new one, have an AMD architecture. 

I had synchronised the path `/matrix`and the path under `/opt` with rsync -ar. So I don't quite understand why I can't log in with my previous data. The database seems to be complete.
