### ISSUE TITLE
Cannot access mautrix-discord appservice

### ISSUE THREAD

**Issue by Sushiman42** [spantaleev/matrix-docker-ansible-deploy#3900]
**Describe the bug**
Attempting to allow M->D avatars to be bridged along with messages. [mautrix-discord documentation](https://docs.mau.fi/bridges/go/discord/relay.html) indicates that access to the appservice is needed in order to direct Discord to the right endpoint to pull avatar images. 

Port 8080, the default in `roles/custom/matrix-bridge-mautrix-discord/templates/config.yaml.j2` does not appear to be passed through the docker container per `docker ps` (and it might conflict with a default traefik port). The systemd file at `matrix-mautrix-discord.service.j2` does not appear to be forwarding any ports from the container like other services.

Relevant portion of my `vars.yml`
> matrix_mautrix_discord_enabled: true
matrix_mautrix_discord_homeserver_public_address: https://bridge._domain_.com (this would be a subdomain reverse proxied to the mautrix-discord appservice's port if available)
>

**Expected behavior**
Ideally, the bridge would be available to pass to Discord through something like a reverse proxy, but that does not seem possible with the currently available configuration files. 

**Additional context**
I am running an external reverse proxy ahead of the playbook's services.

**Comment by spantaleev** [comment]
I initially thought this is about the [Direct media access page](https://docs.mau.fi/bridges/go/discord/direct-media.html) feature, but it's not.

The bridge has another feature for relaying avatars of Matrix users to the Discord side.

Our mautrix-discord config was outdated. I have adapted it to the latest upstream sample configuration in f1c238e73251beeaccecb1b575fd46496b9b091b. Some variable names have changed (e.g. `matrix_mautrix_discord_homeserver_public_address` -> `matrix_mautrix_discord_bridge_public_address`). The playbook will tell you about them when you run it.

We were also not publicly exposing the `/mautrix-discord/avatar/{server}/{id}/{hash}` endpoint, as described in this issue.
This has been fixed in cea437c84440c6841eb32923c9e3a46d72214d48.

That said, I am not using relay mode and cannot test this change. Let me know if it works for you!

**Comment by Sushiman42** [comment]
Impressive work, @spantaleev! It appears to be working just fine, and you've saved me the trouble of needing to reverse proxy it myself. No additional variables needed beyond `matrix_mautrix_discord_enabled: true` in my `vars.yml`.

Thanks so much!!!
