### ISSUE TITLE
Add Matrix Sygnal

### ISSUE THREAD

**Issue by blaluc** [spantaleev/matrix-docker-ansible-deploy#398]
Any plan to include https://github.com/matrix-org/sygnal?

**Comment by spantaleev** [comment]
It's not useful in the general case.

Making use of Sygnal requires that one builds their own modified mobile client apps for iOS/Android. This is complicated and not done by many people at all.

Since most of us don't need it and can't test if it even works properly, no one has worked on this yet.
Still, I'd be happy to merge a PR adding Sygnal support!

**Comment by CodingAnonymous** [comment]
I would love to see that feature! Any progress here? How can I get started on integration sygnal to matrix-docker-ansible-deploy? I would like to make a contribution.

**Comment by chagai95** [comment]
@T3chTobi I think the first step would be to have set up a working sygnal push server with docker, have you done that?
