### ISSUE TITLE
Add matrix group to Nginx server?

### ISSUE THREAD

**Issue by danger89** [spantaleev/matrix-docker-ansible-deploy#412]
Hi,

I follow the following guide:
https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-own-webserver.md#preparation

I want to use my existing reverse proxy server (Nginx), so I tend to disable the built-in Nginx docker container from this project.

I have an existing reverse proxy server running on the host PC (outside docker/not containerized). When running: `usermod -a -G matrix nginx`. It gives the error that the matrix group doesn't exist. Which makes sense since my host OS doesn't have this group. Properly this group is only know within your docker instance. In fact it can result to different GID (Group ids).

So my question: Is it **really** needed I create a `matrix` group on my host OS for nginx? Since in my eyes this is really not nesseary. I hope Nginx only routes the traffic from the server side towards the (synapse/dimension/riot-web) docker image (running on port x).

Or do I really understood something wrong?

Regards,
Melroy van den Berg

**Comment by spantaleev** [comment]
If you've run the playbook, the `matrix` group should have been created by the `matrix-base` role. See here: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/f091df0c48d0851f7450b0a86be96565ed0ed7f0/roles/matrix-base/tasks/setup_matrix_base.yml#L3

The goal of adding the `nginx` user to the `matrix` group is so that the `nginx` user could read the config files generated at `/matrix/nginx-proxy/conf.d/`. This allows you to easily include the Matrix configuration inside your existing nginx webserver.

If you'll be setting up vhosts and reverse-proxying by yourself, you don't need such group membership changes. In any case, I advise that you take a look at (or copy) the configuration from `/matrix/nginx-proxy/conf.d/`, to prevent reverse-proxying mistakes.

**Comment by danger89** [comment]
Thanks. In the last case, this was indeed not clear.

Since method 1 from the Readme explicitly explains how to not use the nginx builtin server at all. Yet the first step was to add the user matrix to the nginx group.

Do you want to update your docs in that regard?

**Comment by spantaleev** [comment]
I've clarified this documentation page in ecd35a8.
