### ISSUE TITLE
change jitsi.DOMAIN to example.DOMAIN ?

### ISSUE THREAD

**Issue by nocci-sl** [spantaleev/matrix-docker-ansible-deploy#419]
Wow... I really appriciate that jitsi is now integrated. So thank you very much for yur steady work. 
I really love it.

But: Is there a way to change the default jitsi.DOMAIN to another subdomain?

reason: My provider has a strict traffic policy and bills a lot if I use more traffic than included. So I just want to make sure that nobody exept my family and friends will find jitsi on my server by just guessing the default subdomain.

So it would be very nice if I could just change the subdomain (and the LetsEncrypt-certificates) in the playbook.

If anyone has a tip it would make me very happy.
Thx.

**Comment by spantaleev** [comment]
The default is found in `roles/matrix-base/defaults/main.yml` and is like this:

```yaml
matrix_server_fqn_jitsi: "jitsi.{{ matrix_domain }}"
```

You can override it via your own `inventory/host_vars/matrix.DOMAIN/vars.yml` file.

It's a bit of security through obscurity.. And it's not enough to just change the Jitsi domain, because your Riot config at `https://riot.DOMAIN/config.json` will also be pointing to your Jitsi server.. Unless you move Riot to another domain as well (via the `matrix_server_fqn_riot` variable).

And still, that's not ideal, because the playbook obtains Let's Encrypt certificates for each domain.. And those certificates and domains end up in [Certificate Transparency](https://en.wikipedia.org/wiki/Certificate_Transparency) logs.. But maybe it goes a long way to prevent access to your Jitsi server for most people.

Perhaps a better solution might be to see if we can lock down Jitsi somehow.. But that may require support from Riot as well. Or we can put it behind HTTP Basic Auth (which hopefully won't break for iframe widgets inside riot-desktop).. Hopefully HTTP Basic Auth is enough to protect the Jitsi web UI, which in turn is enough to make the Jitsi server's video bridge (udp/10000, tcp/4443) not do any meaningful work for others.. I guess it would be, but we'd better confirm it anyway.

I guess it doesn't need to be perfect.. It's enough to kill the web UI, so that external people don't have easy access to create meeting rooms.

**Comment by nocci-sl** [comment]
... 
> It's a bit of security through obscurity.. And it's not enough to just change the Jitsi domain, because your Riot config at `https://riot.DOMAIN/config.json` will also be pointing to your Jitsi server.. Unless you move Riot to another domain as well (via the `matrix_server_fqn_riot` variable).
> 
...
> I guess it doesn't need to be perfect.. It's enough to kill the web UI, so that external people don't have easy access to create meeting rooms.

Thank you very much for your great explainations.

I totally forgot about the `https://riot.DOMAIN/config.json` - so yeah... a HTTP Basic Auth or just disabling the webui at `https://jitsi.DOMAIN/` would be way better.

**Comment by spantaleev** [comment]
I'm guessing HTTP Basic Auth might cause problems for Riot though, while it's trying to set up the Jitsi room, etc.. So maybe that won't work.. Needs testing.

**Comment by hughwilliams94** [comment]
Jitsi seems to have internal support for [authentication](https://github.com/jitsi/docker-jitsi-meet#internal-authentication) based on XMPP credentials (although there are notes of LDAP and JWT tokens), is this perhaps the better route to go down? I am not sure how this ties into the Riot integration.

**Comment by Metzlmane** [comment]
What if I'm already running example.domain jitsi instance (without authentication) and just want to link it in dimension and riot? just put it in both config files?

**Comment by anup92k** [comment]
Here is what I've done : 
![image](https://user-images.githubusercontent.com/51033013/78501963-d6a52600-775e-11ea-9f2f-10c0abfa1a5c.png)

This way, new jitsi widget will be create using my jitsi domain.

**Comment by spantaleev** [comment]
@Metzlmane, I guess what @anup92k says is the way to do it for Dimension.

For riot-web, you can put this in your `inventory/host_vars/matrix.DOMAIN/vars.yml` config to point it to your own Jitsi server's domain:

```yaml
matrix_riot_web_jitsi_preferredDomain: "example.domain.com"
```

-----

I'm closing this issue, because it's no longer relevant. The playbook now supports setting up a [Private Jitsi server](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/CHANGELOG.md#private-jitsi-support), so "security through obscurity" is not necessary.
