### ISSUE TITLE
error manifest for avhost/docker-matrix-riot:v0.17.7 not found

### ISSUE THREAD

**Issue by tvo6** [spantaleev/matrix-docker-ansible-deploy#42]
It seems the playbook tries to install v0.17.7 of the docker image, which cannot be found, as the latest release seems to be v0.17.6 (https://github.com/AVENTER-UG/docker-matrix-riot/releases).

This change in roles/matrix-server/defaults/main.yml does the job : 
```
-matrix_riot_web_docker_image: "avhost/docker-matrix-riot:v0.17.7"
+matrix_riot_web_docker_image: "avhost/docker-matrix-riot:v0.17.6"
```

**Comment by spantaleev** [comment]
For my usage of the playbook, I redefine `matrix_riot_web_docker_image`, because I want to use a custom image (based on the original, but with a small patch of mine). I don't update my custom image so often and I didn't this time, so I haven't ran into the problem of the 0.17.7 image being missing. Looks like it lead to me not finding out about it for a long time.

Thanks for catching/reporting this! :+1: 

I've been too impatient to keep things up to date in the playbook, that I've updated this before it even got released.

It's fixed now!
