### ISSUE TITLE
Federation not working after clean install

### ISSUE THREAD

**Issue by schopenhauer** [spantaleev/matrix-docker-ansible-deploy#421]
The federation does not seem to work properly despite being enabled (e.g. joining rooms on matrix.org does not work) after a clean install on Debian 9. I see the following error message when testing my site with the https://federationtester.matrix.org/.
 
```
WARN: Could not find a valid certificate for <IP address>:8448. See this documentation for instructions on how to fix this.
ERROR: on <IP address>:8448: x509: certificate is valid for matrix.<domain name>, not <domain name>
```

Any advice you can give?

**Comment by aaronraimist** [comment]
For support it is usually better to join our Matrix room `#matrix-docker-ansible-deploy:devture.com` either using a Matrix account on another server or via the Freenode bridge which bridges to the IRC channel #matrix-docker-ansible-deploy.

**Comment by spantaleev** [comment]
Not sure what your domain is, so I can't check, but.. it looks like the Federation Tester is indicating that you have not properly configured [Server Delegation](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/howto-server-delegation.md#server-delegation).

You likely need to set up [Service Discover via .well-known](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-well-known.md).

If you're using Server Delegation via DNS SRV records (described in the Server Delegation guide), you'll need to serve the federation API (port 8448) with a certificate for the base domain, and not for the `matrix.` subdomain. The Server Delegation docs page has some helpful pointers about how to do this. We generally advise against this, because it leads to a more complicated setup.

**Comment by airdogvan** [comment]
How can I join #matrix-docker-ansible-deploy:devture.com?  If I search for this room in my riot client on my server it's not found, if I switch to matrix.org I find all their rooms.
Not sure how to join from my server...

**Comment by spantaleev** [comment]
`/ join #matrix-docker-ansible-deploy:devture.com` should work.

**Comment by airdogvan** [comment]
Thank you so much that did it...
