### ISSUE TITLE
use ldap as auth provider

### ISSUE THREAD

**Issue by tvo6** [spantaleev/matrix-docker-ansible-deploy#43]
I need to use my ldap directory as provider for passwords. During my tests (only with matrix-synapse), I used these lines in `homeserver.yaml` and it worked ok: 

```
password_providers:
    - module: "ldap_auth_provider.LdapAuthProvider"
      …
```

Is there a way to:
* either specifiy these settings in host_vars.yml
* or connect to matrix-synapse afterwards to change these?

Thanks!

**Comment by tvo6** [comment]
I made this commit: [auth-ldap test](https://github.com/tvo6/matrix-docker-ansible-deploy/commit/9cf9a1ec549cf6ab280f8974b41dbd2ce11c523d). But it doesn't seem to work.
I get these errors in log (myuser and the password are the ones from my ldap account):
```
2018-11-27 15:33:03,601 - synapse.access.http.8008 - 233 - INFO - POST-76 - MY_IP - 8008 - Received request: POST /_matrix/client/r0/login
2018-11-27 15:33:03,601 - synapse.rest.client.v1.login - 173 - INFO - POST-76 - Got login request with identifier: {u'type': u'm.id.user', u'user': u'myuser'}, medium: None, address: None, user: u'myuser'
2018-11-27 15:33:03,603 - synapse.metrics - 374 - INFO -  - Collecting gc 0
2018-11-27 15:33:03,614 - synapse.metrics - 374 - INFO -  - Collecting gc 1
2018-11-27 15:33:04,001 - synapse.handlers.auth - 745 - WARNING - POST-76 - Failed password login for user @myuser:mydomain.tld
2018-11-27 15:33:04,003 - synapse.http.server - 85 - INFO - POST-76 - <XForwardedForRequest at 0x7fdce292e7e8 method=u'POST' uri=u'/_matrix/client/r0/login' clientproto=u'HTTP/1.0' site=8008> SynapseError: 403 - Invalid password
2018-11-27 15:33:04,004 - synapse.access.http.8008 - 302 - INFO - POST-76 - 129.88.45.76 - 8008 - {None} Processed request: 0.403sec/0.000sec (0.396sec, 0.000sec) (0.000sec/0.001sec/1) 52B 403 "POST /_matrix/client/r0/login HTTP/1.0" "Mozilla/5.0 (X11; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0" [0 dbevts]
```

Do you know if some package is missing to get ldap auth provider to work?

Thanks.

**Comment by spantaleev** [comment]
Modifying `homeserver.yaml` manually can make it work and it's nice you have verified that.

The next run of the playbook will wipe out your changes though, unless we add support for it somehow.
We currently have 2 auth providers implemented:
- [REST auth](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-rest-auth.md)
- [Shared Secret auth](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-shared-secret-auth.md)

We can probably add support for LDAP as well. Looks like Synapse installs an LDAP password provider module by default.

---------

Looks like you've already started work on adding support for [matrix-synapse-ldap3
](https://github.com/matrix-org/matrix-synapse-ldap3)! That's great!

What's left to do is to toggle the (internal) variable `matrix_synapse_password_providers_enabled` to `true` (see the `if` for it a little more above your changes in `homeserver.yaml`).

The other 2 auth providers need a lot more initialization stuff (including downloading and mounting the libraries), so they do it from `roles/matrix-server/tasks/setup/setup_synapse_ext.yml`. Each one has a dedicated include and a dedicated file (e.g. `setup_synapse_ext_rest_auth.yml`) in that same directory.

You can probably define one more (`setup_synapse_ext_ldap_auth.yml`), which simply does something like this:

```yaml
- set_fact:
    matrix_synapse_password_providers_enabled: true
  when: "matrix_synapse_ext_password_provider_ldap"

- set_fact:
    matrix_synapse_additional_loggers: >
      {{ matrix_synapse_additional_loggers }}
      +
      {{ [{'name': 'ldap_auth_provider', 'level': 'INFO'}] }}
  when: "matrix_synapse_ext_password_provider_ldap"
```

The logging thing is so that an additional logger would be defined, to capture the output of the LDAP auth provider.

--------

Besides this, it looks like the LDAP auth provider supports a few additional optional stuff (filter, `bind_dn`, `bind_password`). We may add support for this now or later, up to you.

In any case, documentation would be appreciated by others! If you don't have the time though, it's okay!

Thanks for contributing and making the playbook better! :+1:

**Comment by spantaleev** [comment]
Oh, you have added support for filter, `bind_dn` and `bind_password` already. That's pretty complete then!

Once you add a few more files in `tasks/setup`, it should work nicely!

**Comment by tvo6** [comment]
OK, thanks for your answers! I just ask myself how can I add support for LDAP as stated in https://github.com/matrix-org/matrix-synapse-ldap3: where should I put the deb or pip package?

**Comment by spantaleev** [comment]
I don't think you need to install this Python package manually.

Looking at `synapse/python_dependencies.py` in the Synapse repository, indicates that the LDAP password provider is installed automatically as part of Synapse.

Maybe once you enable logging, it would tell you more about why it's failing. I don't think it's because the module is missing though.

**Comment by tvo6** [comment]
OK, removing and reinstalling everything does the job.

I start the PRs.

**Comment by spantaleev** [comment]
That's great! I'd be happy to merge it!

A small suggestion I have is to make sure the variable names in playbook are closer in naming to the variables that actually configure the LDAP auth module.

That is to say: 
- for configuring `start_tls`, it's better to have it be (`matrix_synapse_ext_password_provider_ldap_start_tls` -> `matrix_synapse_ext_password_provider_ldap_start_tls`
- for configuring the `uid` in **attributes**, it's better to have it be (`matrix_synapse_ext_password_provider_ldap_attr_uid` -> `matrix_synapse_ext_password_provider_ldap_attributes_uid`)
- for `bind_dn`, it's better to have it be (`matrix_synapse_ext_password_provider_ldap_binddn` -> `matrix_synapse_ext_password_provider_ldap_bind_dn`
- for `bind_password`, it's better to have it be (`matrix_synapse_ext_password_provider_ldap_bindpwd` -> `matrix_synapse_ext_password_provider_ldap_bind_password`)

I guess using names that are closer leads to more consistency and less confusion.

Thank you for your work on adding LDAP support for everyone!

**Comment by tvo6** [comment]
OK, I thought my naming was explicit enough, but I'll make the changes.

**Comment by spantaleev** [comment]
Yes, your naming is good! But making it as identical as possible is probably better and less confusing.
At least that's what we try to do everywhere else in the playbook.

**Comment by tvo6** [comment]
I don't understand why, but the ldap auth provider doesn't seem to work anymore:

- I changed from « test » to « production », so I needed to change LDAP parameters
- I removed everything
- changed the settings in host-vars.yml
- rerun the setup and:
  - the password_providers section is empty in /matrix/synapse/config/homeserver.yaml
  - the postgres database is empty (no relations)

Looking at the git log, I don't see what commit could have broken that; do you have some clue?

**Comment by spantaleev** [comment]
Adding this:

```yaml
matrix_synapse_ext_password_provider_ldap_enabled: true
```

to my `inventory/host_vars/matrix.DOMAIN/vars.yml` file and then rerunning the playbook (even `--tags=setup-synapse,start` is enough) seems to work for me. I can see that `homeserver.yaml` gets regenerated and that `module: "ldap_auth_provider.LdapAuthProvider"` is there.

**Comment by tvo6** [comment]
OK, my bad, I had a typo in my vars file… Sorry for reopening the issue…
