### ISSUE TITLE
Federation failure without matrix_nginx_proxy_base_domain_serving_enabled: true

### ISSUE THREAD

**Issue by bmiller59** [spantaleev/matrix-docker-ansible-deploy#471]
Thank you for this fantastic project! Well built and well documented, and very helpful and flexible.

I just set up my own matrix server recently using this playbook. I was receiving federation `401 Unauthorized` errors when I tried to access rooms from other servers until I added `matrix_nginx_proxy_base_domain_serving_enabled: true` and reran the playbook.

With this set to false (the playbook default), I could not access rooms at matrix.org, for example, and the federation tester (https://federationtester.matrix.org/) was giving me an error about the certificate for `matrix_domain` even thought it should not technically be needed since matrix is installed at `matrix.{{ matrix_domain }}`.

When I set it to true the federation tester stopped complaining and the room access succeeded. 

Perhaps you want to enable ``matrix_nginx_proxy_base_domain_serving_enabled: true` by default for that reason.

Thanks again.

**Comment by spantaleev** [comment]
Hi! Thank you for the kind words!

You were getting these errors, because in order for your server to be hosted at a subdomain (like `matrix.DOMAIN`), while presenting itself as just `DOMAIN`, [Server Delegation](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/howto-server-delegation.md) of some sort must be done.

There are 2 ways to do it:
- (what we recommend) via [well-known](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-well-known.md) files hosted at the base domain manually
- (another more-complicated option) using DNS SRV records

Basically, you had to set up your base domain and make it serve some well-known files, so that federation would start working. You could have done that manually, as described in the [well-known](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-well-known.md) documentation page.

The alternative is to tell the playbook "I don't need my base domain for other purposes.. Please serve it for me", which is what you've done with the `matrix_nginx_proxy_base_domain_serving_enabled: true` flag. If you do this, the playbook will:
- retrieve an SSL certificate for your base domain
- serve a sample page at `https://DOMAIN`
- serve the well-known files at `https://DOMAIN/.well-known/matrix/..`

It's the easiest way to get Server Delegation working, but it can only happen if you don't need your base domain for any other purpose, and you're fine with the playbook taking it over. Not sure how common it is, but I believe that a lot of people need their base domain for other uses.

**Comment by bmiller59** [comment]
@spantaleev Thank for that note about .well-known. I had seen that in the docs, BUT as a someone new to this playbook, I did not realize that I MUST either set the .well-known on the root domain myself, OR set `matrix_nginx_proxy_base_domain_serving_enabled: true` or federation would fail.

I would recommend adding a note to this effect in either `https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-dns.md` or `https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook.md` so that people new to the project realize that one or the other is required for federation to succeed. 

Thank you.

**Comment by spantaleev** [comment]
You ultimately end up on [installing.md](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/installing.md), which explicitly mentions that you need to:

> **finalize the installation process** (required for federation to work!) by Configuring Service Discovery via .well-known

It seems like you've missed that and jumped straight to "creating users" below it or something like that. If you've got suggestions for how we can make it clearer and harder to miss, let me know.

**Comment by bmiller59** [comment]
True enough! RTFM again. ;) That's pretty clear but somehow I missed it. I don't think a further change is needed but at least this issue can serve as a fallback if anyone else misses it and comes looking for solutions here.
