### ISSUE TITLE
Please update irc bridge

### ISSUE THREAD

**Issue by jgoerzen** [spantaleev/matrix-docker-ansible-deploy#474]
0.16.0 is now available

See https://github.com/matrix-org/matrix-appservice-irc/blob/master/CHANGELOG.md

**Comment by spantaleev** [comment]
Since I don't use this bridge, I can't test if upgrading to 0.16.0 succeeds without trouble.

If you've given it a try (with `matrix_appservice_irc_docker_image: "matrixdotorg/matrix-appservice-irc:release-0.16.0"`), please let me know and I'll update the playbook. You can also submit a PR, if you prefer.

---------

Looks like [0.15.0](https://github.com/matrix-org/matrix-appservice-irc/blob/master/CHANGELOG.md#0150-2020-02-05) introduced some breaking changes to the `mappings` format. It's not something we use by default, but it'd still be nice to update our example configuration (in `roles/matrix-bridge-appservice-irc/defaults/main.yml`) to adhere to that new format.

I should post a "Breaking Change" entry in our own `CHANGELOD.md` as well, for people who use this bridge and might be using the old `mappings` format.
