### ISSUE TITLE
populate service_facts failed once

### ISSUE THREAD

**Issue by jolly-jump** [spantaleev/matrix-docker-ansible-deploy#500]
Hi, 

i moved my installation from an 18.04 to an 20.04 but I used an earlier git-version of this ansible script.
I the older version the service_facts did not go through due to this error:
https://github.com/ansible/ansible/commit/bd4fdb1ca23fb043789042074f3f9fa4fb07fbf1
which was somehow only fixed 19 days ago.
Now I tried to reproduce it with the current checkout of this ansible script and the original service_facts.py which does not contain above bug-fix and the error fails to reproduce.

Now I wonder and just want to document it here, that everything seems to be fine, but whoever gets the error, that "populate service_facts" 
Greetings and thanks to all you developers!

**Comment by spantaleev** [comment]
Hi!

It could still fail on the `service_facts` module, I guess.

We apply some workarounds in [roles/matrix-common-after/tasks/start.yml](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/5b8fd44aa7a0659e67ce8bdb7bfb3448e9656d51/roles/matrix-common-after/tasks/start.yml), but only for Archlinux-based servers (which is running a new systemd).

Ubuntu 20.04 also runs a new (and possibly problematic) systemd, but you're likely not running into the problem, because your Ansible already contains that patch..?

We may need to apply the workaround to Ubuntu 20.04 hosts as well, for people running older Ansible while targeting an Ubuntu 20.04 server. So far, the few people who have installed on Ubuntu 20.04 haven't said anything about this, so I'm guessing it's not very widespread.

Installing on Ubuntu 20.04 is a bit "unsupported" for now. See #482

**Comment by jolly-jump** [comment]
Hi, 
somehow the error returned: Using an 20.04 ansible on the same host as the matrix+riot service.
setup-all still runs through,  but "start" does quit with above error.

**Comment by worldofgeese** [comment]
I have the same error on Ubuntu 20.04 every time I start services.

**Comment by spantaleev** [comment]
Someone had reported the bug here: https://bugs.launchpad.net/ubuntu/+source/ansible/+bug/1880359

It will possibly get fixed soon.

In the meantime, you can try running Ansible via Docker (see our docs on how), or to just ignore this error (it shouldn't cause any other problems).
