### ISSUE TITLE
Attempted Ubuntu 20.04 - systemd 245 - Warning

### ISSUE THREAD

**Issue by hungrymonkey** [spantaleev/matrix-docker-ansible-deploy#517]
Hi Everyone, 

I am posting this issue as a warning. You have to update to `ansible 2.9.8+`  for any distro with `systemd 245+` which includes Ubuntu 20.04, Fedora 32, etc.

https://github.com/ansible/ansible/commit/bd4fdb1ca23fb043789042074f3f9fa4fb07fbf1

```
TASK [matrix-common-after : Populate service facts] ****************************************************************************************************************************
fatal: [matrix.domain.com]: FAILED! => {"changed": false, "msg": "Malformed output discovered from systemd list-unit-files: accounts-daemon.service                        enabled         enabled      "}
```

**Comment by hungrymonkey** [comment]
Should we document the issue?

**Comment by hungrymonkey** [comment]
https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/ansible.md

**Comment by pushytoxin** [comment]
Ubuntu ships a broken Ansible, but the bug isn't reported yet, the priority is to have it fixed upstream:
https://bugs.launchpad.net/ubuntu/+source/ansible


Depending on how long it will take to get the maintainer to update Ansible to v2.9.8 or above, it could be a good idea to document this issue, especially since more and more people will opt for running 20.04LTS, all of them will run into this bug.

**Comment by pushytoxin** [comment]
I opened the issue on launchpad, here's the link
https://bugs.launchpad.net/ubuntu/+source/ansible/+bug/1880359

If you have an ubuntu one account, you can mark yourself as affected.

**Comment by hungrymonkey** [comment]
@pushytoxin This bug affects every who attempt to talk to a systemd 245+ distro. Ubuntu 20.04 might be a good start but it will affect everyone.

**Comment by pushytoxin** [comment]
Know of any other distros that ship systemd=245 together with ansible<2.9.7? Fedora is unaffected, and neither is debian (except buster-backports)

**Comment by pushytoxin** [comment]
Sorry, I just realized what you said. So this also affects people who use an older ansible to connect to a remote host with a newer systemd. I only ever used ansible on a localhost connection.
In that case there should definitely be a note on this.

**Comment by spantaleev** [comment]
Indeed! This bug only affects people running **outdated** Ansible against a server with newish systemd (so far that's Archlinux and Ubuntu 20.04, it seems).

Since Ansible has been fixed and there's been a new release since a long time ago, the proper solution seems to be to get it updated.

Ubuntu is just very slow to do this. I remember a similar issue affecting us a few years back, where Ubuntu developers would just not update Ansible for months.

-----

A good workaround is to [Use Ansible via Docker](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/1234cc48c5e1633e44c19ae0f86dfb54eeb0bbe6/docs/ansible.md#using-ansible-via-docker).

Not sure if that would work with `ansible_connection=local` though.


--------

We may also update `roles/matrix-common-after/tasks/start.yml` to apply our workaround (not using `service_facts`) on other distros.

Seems like always using the workaround is a potential solution, but it's kind of ugly (very long output). It may be better to apply it for people who ask for it (perhaps `--extra-vars="avoid_service_facts=yes"`)

**Comment by kgtzy** [comment]
this issue was solved by https://github.com/ansible/ansible/commit/bd4fdb1ca23fb043789042074f3f9fa4fb07fbf1#diff-5fe2fdf32cea9df92893b26b933806b6ff6193d72e0774387459e2b7789f9189

worked for me on ubuntu 20.04 ansible 2.9
hope it helps

**Comment by spantaleev** [comment]
I've added some notes about this via 3fd198e89a6be5
