### ISSUE TITLE
Can't join/list rooms and matrix federation tester gives me wrong message

### ISSUE THREAD

**Issue by rmateusucm** [spantaleev/matrix-docker-ansible-deploy#527]
I've tried to set it up and everything works fine except:

- Can't join/list rooms from matrix.org it gives me 401 unauthorised
- Matrix Federation Tester gives me a Matching Server Name error perphaphs that could be the reason.

The JSON result is: https://federationtester.matrix.org/api/report?server_name=matrix.librelabucm.org

It would really nice if someone could help me because I've set up the main website to proxy to /.well-known/ in Caddy as it said in the guide, thank you so much!

**Comment by aaronraimist** [comment]
It gives that error because you are entering the wrong server name into the tester. You are supposed to use librelabucm.org

https://federationtester.matrix.org/#librelabucm.org it looks like it is setup correctly

It is pretty hard to debug over GitHub issues. Can you join the support room? https://github.com/spantaleev/matrix-docker-ansible-deploy#support You can use a Matrix account on another server or use IRC.

**Comment by rmateusucm** [comment]
I believe it didn't worked because I tried setting up a server before and I had to wait for the key to be revoked and updated by matrix.

So now everything it's working, I believe I can close the issue.
