### ISSUE TITLE
Nginx do not redirect to openid callback endpoint

### ISSUE THREAD

**Issue by hungrymonkey** [spantaleev/matrix-docker-ansible-deploy#534]
Openid requires `https://<homeinstance>/_synapse/oidc/callback` to be active.

https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-synapse.conf.j2#L153

Only `_synapse/admin` and `_synapse/metrics` are created.

https://github.com/matrix-org/synapse/blob/develop/docs/openid.md

**Comment by spantaleev** [comment]
Thanks for the report! Should be fixed now! :+1:

**Comment by hungrymonkey** [comment]
@spantaleev 

May I ask the point of putting metrics behind a flag?

https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/65e50205969eaf4170b37115d6845b43a806797a/roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-synapse.conf.j2#L132

**Comment by hungrymonkey** [comment]
Thanks, I can remove my ugly saml2 patches.

**Comment by spantaleev** [comment]
Indeed, metrics are behind a flag, because we don't want to expose them publicly by default. Things should be private and secure by default.

People that want metrics (`matrix_nginx_proxy_proxy_synapse_metrics`) likely wish to also protect them with HTTP Basic Authentication (`matrix_nginx_proxy_proxy_synapse_metrics_basic_auth_enabled`).

---

Happy to hear you can stick a vanilla playbook now!

**Comment by hungrymonkey** [comment]
I have to finish up my backup patches. However, deploying SAML is awkward. You need to download a key from keycloak and deploy it onto the matrix server for SSO.  I am happy to rip up those patches.
