### ISSUE TITLE
Suggestion for simplifying .well-known setup via nginx proxy

### ISSUE THREAD

**Issue by pjv** [spantaleev/matrix-docker-ansible-deploy#563]
I wanted to do federation TLS on a non-standard port (8443 instead of 8448) so that I could run my server behind Cloudflare proxy and use the SSL certs supplied by Cloudflare. In the process of making the config changes needed to make that work simply, I needed to serve `.well-known` from the nginx server already handling my base domain's website. 

I stumbled onto this nginx trick for making that happen without actually having to create a `.well-known` directory or any files. I don't have time right now to dig far enough into this project's setup to create a PR for you, but I thought it might allow you to simplify the playbook a little for the `.well-known` stuff for federation and let's encrypt.

Here's a piece of my domain's base server nginx config:

```
  location /.well-known/matrix/server {
    default_type application/json;
    return 200 '{"m.server":"matrix.<mydomain>.com:8443"}';
  }
```

**Comment by spantaleev** [comment]
We recommend something similar in [(Option 3): Setting up reverse-proxying of the well-known files from the base domain's server to the Matrix server](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-well-known.md#option-3-setting-up-reverse-proxying-of-the-well-known-files-from-the-base-domains-server-to-the-matrix-server) of our **Configuring well-known** instructions.

It proxies all files under `/.well-known/matrix`, because:
- there's also a `/client` file there that is useful and can contain plenty of options. See the template of [our current `/client` file](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/roles/matrix-base/templates/static-files/well-known/matrix-client.j2)
- these files may even change over time, getting to have more options

What you're recommending works for the general case and is probably even more reliable (because it doesn't depend on the Matrix server being up).

**Comment by pjv** [comment]
What I thought was nice was having nginx directly respond with the `json` so you wouldn't need to even create the directory or the `client` and `server` files on the matrix server. I was thinking that you could replace everything in `.well-known/matrix` and maybe even `.well-known/acme-challenge` in the playbook with a single jinja template for the nginx config in the `matrix-nginx-proxy` container.

Thanks for pointing out the potential complexity of the client json - I did not realize there were so many options in there.
