### ISSUE TITLE
Change default domain from riot. to something else

### ISSUE THREAD

**Issue by ptman** [spantaleev/matrix-docker-ansible-deploy#586]
`matrix_server_fqn_riot`

element.?

chat.?

**Comment by Cadair** [comment]
Probably worth making sure any existing domains continue to be served unless the user wants to disable them, I am likely to just keep using riot. anyway.

**Comment by thedanbob** [comment]
It's not difficult to setup a redirect from the old subdomain to the new one. I'm using the configuration below to redirect `riot.` to `element.`:

```yaml
matrix_server_fqn_riot: "element.{{ matrix_domain }}"

matrix_ssl_domains_to_obtain_certificates_for:
  - "{{ matrix_server_fqn_matrix }}"
  - "{{ matrix_server_fqn_riot }}"
  - "{{ matrix_server_fqn_dimension }}"
  - "{{ matrix_domain }}"
  - "riot.{{ matrix_domain }}"

matrix_nginx_proxy_proxy_http_additional_server_configuration_blocks:
  - |
    server {
      listen {{ 8080 if matrix_nginx_proxy_enabled else 80 }};
      server_name riot.{{ matrix_domain }};
      return 301 https://{{ matrix_server_fqn_riot }}$request_uri;
    }
  - |
    server {
      listen {{ 8443 if matrix_nginx_proxy_enabled else 443 }} ssl http2;
      listen [::]:{{ 8443 if matrix_nginx_proxy_enabled else 443 }} ssl http2;

      server_name riot.{{ matrix_domain }};
      server_tokens off;

      ssl_certificate {{ matrix_ssl_config_dir_path }}/live/riot.{{ matrix_domain }}/fullchain.pem;
      ssl_certificate_key {{ matrix_ssl_config_dir_path }}/live/riot.{{ matrix_domain }}/privkey.pem;
      ssl_protocols {{ matrix_nginx_proxy_ssl_protocols }};
      ssl_prefer_server_ciphers on;
      ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";

      return 301 https://{{ matrix_server_fqn_riot }}$request_uri;
    }
```

Of course, you have to add a new CNAME entry to your DNS and run the procedure for new SSL certs, so it may be worth writing up a doc page.

**Comment by spantaleev** [comment]
The migration is now done! See the changelog entry: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/CHANGELOG.md#compatibility-break-riot-is-now-element

--------

I think what's missing from the @thedanbob's configuration above is `/.well-known/acme-challenge` serving for the HTTP vhost, so that the SSL certificate for the `riot.` subdomain can be renewed.

By the way, there's a built-in way to accomplish such a smooth migration (`riot.DOMAIN` -> `element.DOMAIN`) more easily now: `matrix_nginx_proxy_proxy_riot_compat_redirect_enabled: true`
