### ISSUE TITLE
why do listeners in homeserver.yaml.j2 bind to ['::'] ?

### ISSUE THREAD

**Issue by localguru** [spantaleev/matrix-docker-ansible-deploy#690]
Hi,

I don't understand, why the listeners in `roles/matrix-synapse/templates/synapse/homeserver.yaml.j2` bind to `['::']`, which means that the listener ports bind to all interfaces and listening to the world, firewall configuration not considered. I don't use ipv6, but I bind all workers to  `bind_addresses: ['127.0.0.1'].`, so `localhost` seems to work too.

Cheers,
M.

**Comment by spantaleev** [comment]
Because it only happens in the container (on all network interfaces that are available there). We expose the port to the outside using Docker's port forwarding. In most cases (when `matrix_nginx_proxy_enabled: true`, which is the default), we don't even expose any ports for Synapse, but rather make the nginx container communicate with Synapse over the container network.

**Comment by localguru** [comment]
Thank you!
