### ISSUE TITLE
why is nginx client_max_body for federation higher than homeserver max_upload_size?

### ISSUE THREAD

**Issue by localguru** [spantaleev/matrix-docker-ansible-deploy#692]
Hi,

I don't understand, why `client_max_body_size` for the nginx federation host is higher than `max_upload_size` in `homeserver.yaml`? With the default `max_body_size` the nginx client vhost is limited to 25M, which is less then `max_upload_size: 50M` in `homeserver.yaml`. I understand that. But on the federation port 25*3=75M are possible and synapse only accepts 50M.

roles/matrix-synapse/defaults/main.yml
```
matrix_synapse_max_upload_size_mb: 50
```

/roles/matrix-nginx-proxy/defaults/main.yml
```
matrix_nginx_proxy_proxy_matrix_client_api_client_max_body_size_mb: 25

matrix_nginx_proxy_proxy_matrix_federation_api_client_max_body_size_mb: "{{ (matrix_nginx_proxy_proxy_matrix_client_api_client_max_body_size_mb | int) * 3 }}"
```

**Comment by spantaleev** [comment]
nginx was not limited to 25M. Even though the role `matrix-nginx-proxy` role had such a default, it was only used when the role was used independently of the playbook (related to 4700e803897d2ceb12).

Within the context of the playbook, `matrix_nginx_proxy_proxy_matrix_client_api_client_max_body_size_mb` is redefined in terms of `matrix_synapse_max_upload_size_mb` via `group_vars/matrix_servers`. See here: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/ef07aa8e5df1e8708b6e3a5437570d7677f4cf18/group_vars/matrix_servers#L770

The new default for `matrix_synapse_max_upload_size_mb` is `50`, so `matrix_nginx_proxy_proxy_matrix_client_api_client_max_body_size_mb` also ends up being `50`.

Since 4700e803897d2ceb12, I've also increased the default within `matrix-nginx-proxy` to 50MB, for consistency (and to aid people using `matrix-nginx-proxy` independently).

-----

For `matrix_nginx_proxy_proxy_matrix_federation_api_client_max_body_size_mb`, we use some arbitrarily large value (3 times larger than what the Client API uses).

When the Client API's default max size was limited to ~20MB, it made sense to multiply that a few times to allow for larger federation payloads (`> 50` MB). We now end up with a maximum federation request size of 150MB, which sounds like quite a lot though (certainly more than what any server should send these days). We can consider decreasing it, although it's probably not a big problem leaving it as it is. The [Server-to-Server API spec](https://matrix.org/docs/spec/server_server/r0.1.4) does not mention max payload size, so I'm not sure what a reasonable value would be.

**Comment by localguru** [comment]
Thank you, I understand now.

**Comment by localguru** [comment]
@spantaleev Hi, in case of worker setup do I have to set `client_max_body_size` to 150 on federation port for `/_matrix/media/`? See my last post in PR https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/456
