### ISSUE TITLE
Don't self_build synapse Docker image on ARM

### ISSUE THREAD

**Issue by mattcen** [spantaleev/matrix-docker-ansible-deploy#699]
As of Synapse 1.22, the Docker image is build not just for amd64, but also for [armv7 and arm64](https://hub.docker.com/r/matrixdotorg/synapse/tags). We should update the code to make use of these pre-built images rather than self-build on ARM.

I know that this line will need to change to include the new architectures:

https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/group_vars/matrix_servers#L924

I'm not sure yet if any other changes are needed; doing some other stuff currently, so don't have a chance to dive into it in any greater detail yet.

**Comment by mattcen** [comment]
Ah, I just found 7d211b71e2123ba0a62f2264497c6d4696243e61, which discusses this.

> I can't them on Docker Hub yet

There's a missing word here. Can't *see* them on Docker Hub? They're definitely there as of this comment.

**Comment by spantaleev** [comment]
We had a discussion in the **Synapse Admins** room about this ([here](https://matrix.to/#/!ehXvUhWNASUkSLvAGP:matrix.org/$jN2AdCvLqGcxUKQNUKTvcSBjQGaiNv0HWiuG7rjEo3c?via=matrix.org&via=hacklab.fi&via=kapsi.fi)). It seems like the `amd64` image is being prioritized and pushed first. Images for other architectures follow about an hour later.

In 56ebeb1ae26ecc, I've reverted 7d211b71e2123ba just now, which fixes this issue.

Because non-`amd64` images will always be pushed with a delay, we'll either have to **delay playbook updates until all images are available** (1-2 hours later), or we'll have to think of some other mechanism to handle ARM (**perhaps a separate version variable for ARM, which we update independently**?).

**Comment by mattcen** [comment]
Ah yes, I did notice [that was happening](https://github.com/matrix-org/synapse/blob/develop/.circleci/config.yml#L28) when I was reviewing https://github.com/matrix-org/synapse/pull/7921. I guess it didn't occur to me you'd be updating the playbook quite so rapidly after a new image release 😄 

Yeah, I'm not sure of the best way to solve this one either.
