### ISSUE TITLE
can't use builtin certbot if my nginx is running on host

### ISSUE THREAD

**Issue by makayabou** [spantaleev/matrix-docker-ansible-deploy#712]
I use my nginx proxy on host to serve apps.
So, as port 80 is already used, I can't have playbook retrieving ssl certs for me with lets encrypt.

**Comment by spantaleev** [comment]
You're supposed to stop your webserver, perform the installation, and then bring it back up.

You can follow our [using your own webserver docs page](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-own-webserver.md) for solutions. Since you're using your own nginx server, it would be fairly easy.
