### ISSUE TITLE
Setup-all creates directory instead of configuration file

### ISSUE THREAD

**Issue by TheNyneR** [spantaleev/matrix-docker-ansible-deploy#722]
Hello again!

I tried running the `setup-all` tag today and got the following error:

```
fatal: [<ip>]: FAILED! => {
    "changed": false,
    "diff": [],
    "invocation": {
        "content": "CENSORED: content is a no_log parameter",
        "dest": "/srv/synapse/client-element/config.json",
        "group": "matrix",
        "mode": 420,
        "module_args": {
            "content": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "dest": "/srv/synapse/client-element/config.json",
            "group": "matrix",
            "mode": 420,
            "owner": "matrix"
        },
        "owner": "matrix"
    },
    "msg": "can not use content with a dir as dest"
}
```

The `/srv/synapse/client-element/` folder contains three sub-folders `config.json`, `nginx.conf` and `welcome.html`. I guess something went wrong while creating these configuration files and they were created as folders.

I don't know if this has something to do with it but I have to specify the `-c` parameter as `paramiko` to even connect to my server.

**Comment by spantaleev** [comment]
`/srv/synapse`? We are not supposed to be touching anything in `/srv`. Most directories and files we create are in `/matrix`.

`client-element` under a `synapse` directory? This looks even more bizarre.

**Comment by TheNyneR** [comment]
I have set `matrix_base_data_path: /srv/synapse` in my `vars.yml` file.

**Comment by spantaleev** [comment]
We recently had this happen to someone else. It's very rare, but it could happen if the systemd services are still there and trying to start, while you're messing around with the data directories (deleting files, etc.).

It was happening because mounting files/directories with the `-v` flag for `docker run` (as we were usually doing) meant that Docker would automatically create any missing paths as directories. This is clearly wrong and magic we don't want happening.

See 1fca917ad1310384 and 75f9fde7a48c11 for more details.
