### ISSUE TITLE
ansible_connection=local -> breaks playbook

### ISSUE THREAD

**Issue by digitalkram** [spantaleev/matrix-docker-ansible-deploy#753]
hi there,

when using a cofiguration that works fine over ssh and an identical `inventory/hosts` file with the only difference that an `ansible_connection=local` is appended when run locally on the target machine the playbook breaks with the following message (the repos are on the same commit id for sure: 9dc023c558e3f66ac80342a60711b567237558ea):
```
TASK [matrix-synapse : Ensure Synapse homeserver config installed] ***************************************************************************************************************************************************************************
fatal: [matrix.digitalkr.am]: FAILED! => {"msg": "An unhandled exception occurred while templating '{{ matrix_synapse_configuration_yaml|from_yaml|combine(matrix_synapse_configuration_extension, recursive=True) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ matrix_synapse_configuration_extension_yaml|from_yaml if matrix_synapse_configuration_extension_yaml|from_yaml is mapping else {} }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Unexpected templating type error occurred on ({{ matrix_synapse_configuration_extension_yaml|from_yaml if matrix_synapse_configuration_extension_yaml|from_yaml is mapping else {} }}): a string or stream input is required"}
```

Another slight difference is that the ansible on the local machine (so when using ssh for ansible) is 2.9.10 with python version = 3.7.9 (macOS) while on the target machine it is: ansible 2.9.6 with python version = 3.8.5 (Ubuntu 20 LTS).

`inventory/hosts` file on the local (macOS) machine:
```
[matrix_servers]
matrix.MYDOMAIN ansible_host=MYPUBIPv4 ansible_ssh_user=someuser become=true become_user=root
```
`inventory/hosts` file on the remote/target (Ubuntu) machine:
```
matrix.MYDOMAIN ansible_host=MYPUBIPv4 ansible_ssh_user=someuser become=true become_user=root ansible_connection=local
```

Any hint on what I need to change to get it running on the target machine would be very appreciated!

Thanks :-)

**Comment by spantaleev** [comment]
Perhaps there's some bug in Ansible 2.9.6. I don't have Ubuntu 20.04 LTS to test though, nor should we spend much time tracking bugs that will never get fixed (or rather, that have been fixed already, but Ubuntu developers don't care to push a minor Ansible upgrade).

Ubuntu is notoriously bad at keeping things up to date, especially on LTS. It's a joke of a distribution.
Here's some evidence to that: https://bugs.launchpad.net/ubuntu/+source/ansible/+bug/1880359

Ansible 2.9.6 is buggy in terms of other things as well (as the above bug report shows). These have been fixed for a long time, but don't expect to see these fixes on Ubuntu 20.04 any time soon, given that the above bug has been known for 7 months already and they haven't maintained that package at all.

Because all "stable" distributions use old versions of Ansible, running Ansible on the server itself could be problematic. I guess the best thing to do (unless you're running Arch on your server) is to just run Ansible from another computer (Linux + running Ansible in Docker, unless you have a new Ansible package; MacOS with new Ansible installed via `brew`, etc., or with running Ansible in Docker).

**Comment by k0gen** [comment]
Yes I can confirm that this is due to buggy Ansible. Simple `pip install ansible` updated mine to version 2.10.4 and everything is working as it should.

**Comment by digitalkram** [comment]
Thank you @spantaleev and @k0gen for your replies. I can confirm that ansible 2.10.4 worked for me to.
