### ISSUE TITLE
Cannot find room on other server, cannot communicate with people on other server

### ISSUE THREAD

**Issue by feydreva** [spantaleev/matrix-docker-ansible-deploy#789]
Hello, 

Thank you for the great work !

It seems I have a federation issue.
I first ran the playbook, with all my options configured, without any issue.
the check up command ran OK
and at the step : finalize the installation process (required for federation to work!) by Configuring Service Discovery via .well-known
I decided to go with option 2 : Serving the base domain from the Matrix server via the playbook : matrix_nginx_proxy_base_domain_serving_enabled: true

I ran the install command, the start command, and the check command, but it gave me some SSL error, that the element.DOMAIN didnt match de DOMAIN certificat.
https://federationtester.matrix.org/  also confirmed that.

Few minutes later, I did the install command again, the startup command, the check-up and all ran without any issue.
Now https://federationtester.matrix.org/  is telling me everything is ok.

My issue now is that if I want to add a room from an another server, I get an error.
I I do Explore room, choose the matrix.org server, I get this error : 
Failed to find any key to satisfy VerifyJsonRequest(server=DOMAIN, key_ids=['ed25519:a_SPfg'], min_valid=1610507198189)
if I try to send message to a person on another server, I get  : Not possible to create direct message. Please check user
If I try from another working server, to send myself an error, I get an internal servor error from the other client.

Not sure on what to do next :/
Thank you for your help

**Comment by spantaleev** [comment]
Did you by any chance run another Matrix server at the same domain in the past?

**Comment by feydreva** [comment]
No 1st time.

Anyway.. Woke up this morning and it worked perfectly..
I can look at room in other domain, I can chat with user in other domain..

I guess it takes some time for the federation to kick-in ?

anyway, thank you for this great play book..
installing Matrix looked like a daunting task, and was made easy using this playbook.

**Comment by spantaleev** [comment]
Yep, it make take a while for federation to start working (especially if your settings were incorrect when you first gave it a try).

Thanks for the kind words! 🙇‍♂️

**Comment by xthursdayx** [comment]
I'm having this same issue after creating a new Matrix server at the same domain where I previously ran one. I previously sued this playbook to run a Matrix on an Ubuntu VM on my home server, but yesterday for a variety of reasons I decided to scrap the VM, created a new VM and then ran this playbook with my same vars.yml. Since then I've been getting the error `Failed to find any key to satisfy VerifyJsonRequest(server=my.domain, key_ids=['ed25519:a_wGBG'], min_valid=1611072098851)` when I try to search public rooms on matrix.org. 

The ansible self-check shows no error and the matrix federation checker shows that my server is federated without any issues. My assumption is that somewhere (matrix.org? vector.im) my matrix server's domain is associated with a specific device key that no longer matches since I created the new VM, so my server isn't appropriately federating. 

Any idea if this is the case or how I might be able to fix it?

**Comment by spantaleev** [comment]
Scrapping the VM while you're still in federated rooms is a bad idea.

Do you at least have the old signing key?

**Comment by xthursdayx** [comment]
Yeah, I realized that after the fact unfortunately.... But yes, I do still have my security key, though I set up a new one when I created this VM. I do still have access to the previous VM (I backed it up before creating the new one), so if its my only option, I could bring it back online, leave the federated rooms and then move back to this new VM, but I'd like to avoid that if possible.

**Comment by spantaleev** [comment]
You can put the old key in `homeserver.yaml`'s `old_signing_keys` using `matrix_synapse_configuration_extension_yaml`.

Take a look at #738.

To see what `old_signing_keys` needs to look like, see here: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/39ea3496a4a74d52f991cba1dd52993eee97b286/roles/matrix-synapse/templates/synapse/homeserver.yaml.j2#L1433-L1446

**Comment by xthursdayx** [comment]
Okay, thanks a lot for the help. I'll give it a try.

**Comment by airdogvan** [comment]
Had a server at same address but had to reinstall and lost the key.  Is there something I can do or am I definitively out?
