### ISSUE TITLE
An SMTP server rejected the validation email

### ISSUE THREAD

**Issue by pushytoxin** [spantaleev/matrix-docker-ansible-deploy#792]
When sublmitting emails to external SMTP servers, matrix-mailer identifies itself with just `matrix-mailer`

In this case, the restrictive SMTP server rejected the validation message.

Proposal: send the whole FQDN when sending emails

```
Jan 13 15:22:03 mx0 matrix-mailer[1728680]: 2021-01-13 14:22:03 1kzh2B-00000K-0T **  clientregmail@clientmail.com R=dnslookup T=remote_smtp H=spool.mail.gandi.net [217.70.178.1] X=TLS1.2:ECDHE-RSA-AES256-GCM-SHA384:256 CV=yes: SMTP error from remote mail server after RCPT TO:<clientregmail@clientmail.com>: 504 5.5.2 <matrix-mailer>: Helo command rejected: need fully-qualified hostname
```

**Comment by spantaleev** [comment]
Hmm.. Yeah, we were starting the matrix-mailer container with `--hostname=matrix.DOMAIN`, but that started causing issues lately due to Docker 20.10's internal DNS.

`--hostname=matrix.DOMAIN` makes matrix-mailer believe it's at that hostname, which (I guess) sets `primary_hostname = ...` to `matrix.DOMAIN`, which is what we want.

However, Docker `>= 20.10` considers matrix-mailer to also be `matrix.DOMAIN`, so now **all other containers** on the `matrix` network (bridges, ma1sd, Synapse, etc.) get referred to matrix-mailer when they try to DNS-resolve `matrix.DOMAIN`. That's awful, but I imagine that it's some new Docker feature (well, bug for us). I couldn't find it documented though, so I don't know..

--------------

I guess that we'd like to avoid using `--hostname` (to avoid this Docker DNS "feature"), but we'd still like matrix-mailer (EXIM) to think its hostname is `matrix.DOMAIN`.

We can accomplish this by setting `primary_hostname` in the exim configuration.

Unfortunately, it's not easy to accomplish this right now.

I was thinking we should introduce another environment variable called `PRIMARY_HOSTNAME` and then have `primary_hostname = ${env{PRIMARY_HOSTNAME}{$value}{}}` in the exim configuration.

Unfortunately, I've found out that the `primary_hostname` exim configuration option does not expand environment variables (like all other configuration options).

So it would need to be more complicated than this.. Looking into a better fix.

**Comment by spantaleev** [comment]
If you update and rerun the playbook, you should find `matrix-mailer` automatically using `matrix.DOMAIN` as the hostname.

Thanks for reporting this issue! 👍 

For posterity, I'll mention #748 and https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/7593d969e316cc0144bce378a5be58c76c2c37ee

**Comment by pushytoxin** [comment]
That fixed it, nice job!
