### ISSUE TITLE
matrix-bridge-appservice-discord, matrix_appservice_discord_bot_token should also be string-quoted

### ISSUE THREAD

**Issue by skepticalwaves** [spantaleev/matrix-docker-ansible-deploy#828]
Comparing this
https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/roles/matrix-bridge-appservice-discord/templates/config.yaml.j2#L36

To the line above, the line above contains "|string"

When configs are generated, the token string is not quoted.

**Comment by spantaleev** [comment]
It's not `|string` which does quoting. We have `|string` for the `clientID` (`matrix_appservice_discord_client_id`), because this client id is usually a number and ends up as a number in the configuration. A combination of `|string` and `to_json` ensure proper quoting for this number-like value.

`botToken` (`matrix_appservice_discord_bot_token`) is some string in any case. It wasn't quoted explicitly, because there's usually no need to quote strings in YAML. There's only a need to do it, if it's ambiguous whether something is one type of value or another, or if the string contains some special characters.

Since we can't be sure what kind of characters end up in `matrix_appservice_discord_bot_token` and whether it needs quoting, I've added `|to_json` to it too. Better to be safe.

**Comment by skepticalwaves** [comment]
Ah okay, thanks. New to YAML. I noticed that botToken can have "special" characters so I think explicit quoting makes sense. Thanks!
