### ISSUE TITLE
Registering user problem

### ISSUE THREAD

**Issue by nowatbuer** [spantaleev/matrix-docker-ansible-deploy#866]
According to
https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/registering-users.md I tried to register a user via:
ansible-playbook -i inventory/hosts setup.yml --extra-vars='username=admin password=XXXXXXXX admin=yes  --tags=register-user'
This leads to:
fatal: [matrix.<mydomain>]: FAILED! => {"changed": false, "msg": "The `server_path_postgres_dump` variable needs to be provided to this playbook, via --extra-vars"}
I added the variable and the error message changed:
ansible-playbook -i inventory/hosts setup.yml --extra-vars='username=admin password=XXXXXXXX admin=yes server_path_postgres_dump=/var/postgres/dumpfile --tags=register-user'
TASK [matrix-postgres : Fail if provided Postgres dump file doesn't exists] ***********************************************************************************************************************
fatal: [matrix.<mydomain>]: FAILED! => {"changed": false, "msg": "File cannot be found on the server at /var/postgres/dumpfile"}

Which value should server_path_postgres_dum have?
Thanks 
Norbert

**Comment by spantaleev** [comment]
It sounds like you're not in `--tags=register-user`, but in `--tags=import-postgres`. Something doesn't sound right.

Likely because your command is: `ansible-playbook -i inventory/hosts setup.yml --extra-vars='username=admin password=XXXXXXXX admin=yes --tags=register-user'`

See where the ending quote is. It's after `register-user`, while it should have been after `yes`, like this: `ansible-playbook -i inventory/hosts setup.yml --extra-vars='username=admin password=XXXXXXXX admin=yes' --tags=register-user`

**Comment by nowatbuer** [comment]
Thanks, stupid mistake from my side. It works.
