### ISSUE TITLE
Enable exposing metrics on a host port

### ISSUE THREAD

**Issue by Cadair** [spantaleev/matrix-docker-ansible-deploy#898]
Especially with workers, having to proxy all the metrics is not implemented and generally a pain.

**Comment by MTRNord** [comment]
I especially need this now as I have some kind of performance issue still (aka workers brought 0 improvement) and without metrics I am unable to debug that

**Comment by HarHarLinks** [comment]
You're right, I confused it with the default `matrix_synapse_workers_preset`
Either way I think the above code could in theory be manually added to `matrix_nginx_proxy_proxy_matrix_additional_server_configuration_blocks` by the admin, or be added to matrix-domain.conf.j2 instead of matrix-synapse.conf.j2 to be automatically enabled (if there are any) when `matrix_nginx_proxy_proxy_synapse_metrics` enables proxying of the main thread.
