### ISSUE TITLE
stderr: 'psql: error: could not translate host name "matrix-postgres" to address: Try again'

### ISSUE THREAD

**Issue by hanthor** [spantaleev/matrix-docker-ansible-deploy#994]
```
/usr/bin/env docker run --rm --user=997:1000 --cap-drop=ALL --env-file=/matrix/postgres/env-postgres-psql --network matrix --mount type=bind,src=/tmp/matrix-postgres-init-additional-db-user-and-role.sql,dst=/matrix-postgres-init-additional-db-user-and-role.sql,ro --entrypoint=/bin/sh docker.io/postgres:13.2-alpine -c 'psql -h matrix-postgres --file=/matrix-postgres-init-additional-db-user-and-role.sql'

stderr: 'psql: error: could not translate host name "matrix-postgres" to address: Try again'

```

I get the same error when I try to run the same command from the commandline

**Comment by spantaleev** [comment]
It probably indicates that Postgres fails to start.

Check `journalctl -fu matrix-postgres`.

What is your server's CPU architecture?

**Comment by hanthor** [comment]
Apr 12 12:31:20 synapse matrix-postgres[15398]: 2021-04-12 12:31:20.233 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
Apr 12 12:31:20 synapse matrix-postgres[15398]: 2021-04-12 12:31:20.233 UTC [1] LOG:  listening on IPv6 address "::", port 5432
Apr 12 12:31:20 synapse matrix-postgres[15398]: 2021-04-12 12:31:20.235 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
Apr 12 12:31:20 synapse matrix-postgres[15398]: 2021-04-12 12:31:20.242 UTC [13] LOG:  database system was interrupted; last known up at 2021-04-12 12:24:21 UTC
Apr 12 12:31:20 synapse matrix-postgres[15398]: 2021-04-12 12:31:20.440 UTC [13] LOG:  database system was not properly shut down; automatic recovery in progress
Apr 12 12:31:20 synapse matrix-postgres[15398]: 2021-04-12 12:31:20.444 UTC [13] LOG:  redo starts at 0/1C56A08
Apr 12 12:31:20 synapse matrix-postgres[15398]: 2021-04-12 12:31:20.444 UTC [13] LOG:  invalid record length at 0/1C56AF0: wanted 24, got 0
Apr 12 12:31:20 synapse matrix-postgres[15398]: 2021-04-12 12:31:20.444 UTC [13] LOG:  redo done at 0/1C56AB8
Apr 12 12:31:20 synapse matrix-postgres[15398]: 2021-04-12 12:31:20.455 UTC [1] LOG:  database system is ready to accept connections
Apr 12 12:31:26 synapse matrix-postgres[15398]: 2021-04-12 12:31:26.444 UTC [24] WARNING:  there is already a transaction in progress

**Comment by hanthor** [comment]
`root@synapse:~# /usr/bin/env docker run --rm --user=997:1000 --cap-drop=ALL --env-file=/matrix/postgres/env-postgres-psql --network matrix --mount type=bind,src=/tmp/matrix-postgres-init-additional-db-user-and-role.sql,dst=/matrix-postgres-init-additional-db-user-and-role.sql,ro --entrypoint=/bin/sh docker.io/postgres:13.2-alpine
root@synapse:~# /usr/bin/env docker run --rm --user=997:1000 --cap-drop=ALL --env-file=/matrix/postgres/env-postgres-psql --network matrix --mount type=bind,src=/tmp/matrix-postgres-init-additional-db-user-and-role.sql,dst=/matrix-postgres-init-additional-db-user-and-role.sql,ro --entrypoint=/bin/sh docker.io/postgres:13.2-alpine -c 'psql -h matrix-postgres --file=/matrix-postgres-init-additional-db-user-and-role.sql'
psql: error: could not translate host name "matrix-postgres" to address: Try again
root@synapse:~#`

**Comment by ubergeek77** [comment]
I experienced this exact same issue, but I can confirm @hanthor 's workaround did the trick for me.

Context: I set a server up today, and after a few hours, I wanted to increase my server's upload speed. I set `matrix_synapse_max_upload_size_mb` accordingly, than re-ran the playbook with the `setup-all` ***and*** `start` tags at the same time. *This is what produced the Postgres error described in this issue.*

To fix, I simply ran these three commands:

- `ansible-playbook -i inventory/hosts setup.yml --tags=start`
- `ansible-playbook -i inventory/hosts setup.yml --tags=setup-all`
- `ansible-playbook -i inventory/hosts setup.yml --tags=start`

This successfully reconfigured my server to the change I made, and there were no more failures. Notice that I ran `start` twice - this is because the setting did not seem to have taken effect after `setup-all`, I had to run `start` to get the changes to apply.

**Comment by thedanbob** [comment]
To expand on what @spantaleev said, this error indicates that a docker container tried to access your database but couldn’t find it, most likely because the `matrix-postgres` container wasn’t running. (Occasionally I’ve seen it from a DNS issue with docker itself and you have to restart docker.) If I remember correctly, some of the steps in `setup-all` assume the database is available if it’s detected to exist. Evidently your database container wasn’t running for some reason so `setup-all,start` stopped partway through. Once you ran `start` and your database was back up, running `setup-all,start` would have worked again.
